### ISSUE TITLE
No focus for X11 window if mouse is not over it, despite forceinput

### ISSUE THREAD

**Issue by raffaem** [hyprwm/Hyprland#1022]
I'm on the git version of hyprland:
```
❯ pacman -Qm | grep hyprland
hyprland-git r2046.0634abf-1
waybar-hyprland 0.9.15-1
```

I installed the release version of albert:
```
pacman -S albert
```

I want to launch it through the X protocol as it doesn't work well with Wayland, see [here](https://github.com/albertlauncher/albert/issues/958).

I've put this in my config file:
```
windowrule = center,^(albert)$
windowrule = forceinput,^(albert)$
exec-once = QT_QPA_PLATFORM=xcb albert
```

After albert is launched:
```
albert &; disown
```

And shown:
```
albert show
```

The floating window does not receive focus if the mouse is not over it, despite the `forceinput`.

**Comment by raffaem** [comment]
I can still obtain focus through the `movefocus` dispatcher, but it seems it is because it moves the mouse

**Comment by vaxerski** [comment]
any other app besides albert? It requires a fuckton of deps.

**Comment by raffaem** [comment]
sorry I don't think I have any other XWayland apps installed.

I also don't use albert anymore.

**Comment by niki-on-github** [comment]
Since i discovered the issue while implementing [noinitialfocus](https://github.com/hyprwm/Hyprland/compare/main...niki-on-github:Hyprland:feature/noinitialfocus), here is a short description where to look if you also have such a problem:
The app has probably met one of [these rules](https://github.com/hyprwm/Hyprland/blob/379597e78f512ff2d64a83ba3eb21b7a3444d4f9/src/managers/XWaylandManager.cpp#L176) which is why `m_bNoInitialFocus = true;` was set and therefore the window don't get the [initalFocus](https://github.com/hyprwm/Hyprland/blob/379597e78f512ff2d64a83ba3eb21b7a3444d4f9/src/events/Windows.cpp#L401). By setting `forceinput` you have ensure to get the initialFocus because in [this line](https://github.com/hyprwm/Hyprland/blob/379597e78f512ff2d64a83ba3eb21b7a3444d4f9/src/events/Windows.cpp#L394) if statement we override the  `m_bNoInitialFocus` to false.

**Comment by EpsilonKu** [comment]
> any other app besides albert? It requires a fuckton of deps.

Can confirm on `ulauncher` and `catapult` on GDK_BACKEND=x11

**Comment by LorenzoBettini** [comment]
> I can still obtain focus through the `movefocus` dispatcher, but it seems it is because it moves the mouse

So how do you use the movefocus? In a key binding or in a window rule?

**Comment by izmyname** [comment]
Is this still a problem?

**Comment by alba4k** [comment]
@raffaem

**Comment by raffaem** [comment]
as I said I don't use albert anymore and don't user hyprland either for the time being.

Closing as the issue is now moot.
