### ISSUE TITLE
Spotify inbetween workspaces

### ISSUE THREAD

**Issue by SLaItEr-lx** [hyprwm/Hyprland#1031]
Distro: Arch Linux
Version Hyprland: 0.18

Issue:
When I start Spotify with Wofi then it starts, but it does not show on any workspace. 
Lets say I have foot on workspace1 and I start Spotify on workspace to.  Workspace 2 stays empty but when I switch back to workspace 1 I see the spotify screen passing by. When I switch back to workspace 2 it passes again like it is on a hidden workspace in between 1 and 2. 

It is not a floating nor a xwayland issue (so it seems) since other xwayland stuff does not show this kind of behavior. 

![Screenshot_2022-11-16-22-25-19_9230](https://user-images.githubusercontent.com/73286046/202299072-3201187e-f064-464d-9fe4-fb3b6cb243cc.png)

**Comment by DashieTM** [comment]
Spotify is shotty, the way it spawns windows means it can't be tiled properly. I suggest using a script that will tile it after like 500ms, alongside a windowrule to spawn it in the middle of the screen. Not perfect, but yeah, it's what it is.
Otherwise I can recommend ncspot, uses less resources as it is a cli tool, but let's you listen to music as well so..

**Comment by vaxerski** [comment]
I believe this is long fixed
