### ISSUE TITLE
Menus don't work in Reaper

### ISSUE THREAD

**Issue by sl4v3** [hyprwm/Hyprland#1108]
This is a bug that also existed in sway until a few months ago (it has at least been fixed in the git version of sway). When using Reaper (a digital audio workstation), when clicking on any menu item, the menu briefly appears then immediately disappears making the software pretty much unusable.

**Comment by vaxerski** [comment]
which commit in sway fixed this?

**Comment by sl4v3** [comment]
It looks like #6461
https://github.com/swaywm/sway/pull/6461

Here is a thread talking about it:
https://github.com/swaywm/sway/issues/6324

The behavior in hyprland isn't exactly the same, but it's similar so I'm guessing it's the same bug or at least related.  In hyprland the menus appear in the center of the screen and immediately disappear.  In sway they'd appear where you'd expect them to appear and stay on the screen a bit longer.

**Comment by mgil2** [comment]
The actual fix on the sway side comes in the form of:

[swaywm/sway#6764](https://github.com/swaywm/sway/pull/6764)

The fix sl4v3 posted was negated in favor of:
[swaywm/sway#2103](https://github.com/swaywm/sway/pull/2103/commits/74799937cf95205c2ff16da9dc7dcaea47ce7116)

**Comment by vaxerski** [comment]
doesn't matter, hyprland needs a different patch before that

**Comment by vaxerski** [comment]
mostly fixed with fcf1bafb098c8f756550195269dcd95202124277 and 668842124067f9b6513edf1c28478bec12d709a0

They work, but sometimes don't get the focus when hovered on for the first time. 

Generally I am pretty content with the current status, so I will close this. I don't wanna focus on legacy X11 apps, as simply the fact that they use X11 in such an abhorrent way (additionally X11 being abhorrent itself...) is more of their problem rather than mine.

**Comment by jaketso** [comment]
Is it possible to investigate this problem again? I can't use reaper at all on hyprland. The menus open like once out of 25 tries.
