### ISSUE TITLE
Pinned window cannot be made fullscreen without unpinning first

### ISSUE THREAD

**Issue by mcginty** [hyprwm/Hyprland#1147]
This is at least true with mpv: if I'm playing a video that I've made floating, I can fullscreen. However, if I then pin it and try to fullscreen it won't work until I unpin it first.

It *seems* like it should be possible to fullscreen while pinned.

Thanks for making Hyprland!

**Comment by vaxerski** [comment]
intentional design.

Fullscreening a pinned window would have to remove its pinned status. More intuitive to leave as is.

**Comment by maximbaz** [comment]
Hi @vaxerski, there are a couple downsides with leaving it as it is that I wanted to share with you: 

- the native app's bindings to toggle fullscreen status (mpv's `f`, in this case) "suddenly" don't work if window is pinned
- it isn't possible to make a hyprland keybinding that would just toggle fullscreen status of floating pinned window

For the latter, instead of `pin` dispatcher which currently _toggles_ pinned status, we'd have to do something like:

```
bind SUPER, f, pin, disable (not toggle, always disable)
bind SUPER, f, fullscreen
bind SUPER, f, pin, enable
```

And use this binding (also for non-floating windows, which feels a bit weird, but I wouldn't want to have two separate shortcuts to toggle fullscreen).
This idea also assumes, that I want _all_ floating windows to be pinned, which might not be the case (I could personally live with it).

Maybe Hyprland could do this logic internally on `fullscreen` dispatcher? But to make it proper, it'd have to keep a state of whether the app was pinned, before it enters fullscreen, and restore that status upon exit?

Coming from sway, I want also to share how sway does this: it simply doesn't remove the pinned state from the fullscreen window! In other words, if you are on a workspace 1, you fullscreen a pinned window, press binding to go to workspace 2, you still see the fullscreen video, but when you unfullscreen it, you'll see that you are in fact on workspace 2 now.

**Comment by vaxerski** [comment]
> Coming from sway, I want also to share how sway does this: it simply doesn't remove the pinned state from the fullscreen window! In other words, if you are on a workspace 1, you fullscreen a pinned window, press binding to go to workspace 2, you still see the fullscreen video, but when you unfullscreen it, you'll see that you are in fact on workspace 2 now.

nope it's definitely not gonna work like that.

I can make it remove the pin status, but definitely not this.

**Comment by maximbaz** [comment]
Personally I agree 😁 sway's method has weird consequences, such as keyboard focus can get stolen after moving to another workspace, and the fullscreen window becoming unfocused. I like your idea a lot better, it's both intuitive and still usable with one shortcut (Hyprland's or mpv's) - press `f` on a floating pinned mpv, and it gets unpinned and fullscreen, press `f` again and it's back floating and pinned as it was before 👍

**Comment by ymnejmi** [comment]
> nope it's definitely not gonna work like that.
is there a specific reason for this like maybe security, could it not even be a togglable parameter or something?or is there perhaps a valid workaround?

**Comment by vaxerski** [comment]
I dont understand

**Comment by vaxerski** [comment]
could be

**Comment by Root-Core** [comment]
I agree that restoring the pinned state would be nice.
Maybe restoring the status after unfloating and refloating would also be nice.

**Comment by littleblack111** [comment]
any updates

**Comment by littleblack111** [comment]
can be closed per https://github.com/hyprwm/Hyprland/commit/65f66dcf0d38533a383212ca440fdea0163be276

**Comment by expenses** [comment]
It wasn't totally clear from this issue but to clarify for whoever else stumbled upon this, you can fix this by adding
```
binds {
  allow_pin_fullscreen=true
}
```
to your config.
