### ISSUE TITLE
movefocus in a workspace with fullscreen windows only cylces windows in one direction

### ISSUE THREAD

**Issue by Daxtorim** [hyprwm/Hyprland#1235]
When opening more than 2 windows in a workspace and toggling fullscreen the `movefocus` dispatcher only cycles windows in one direction.

It would be nice if `movefocus` could also cycle in reverse order based on given direction, i.e.:
- `movefocus l` and `movefocus u` would be equivalent to `cyclenext prev`
- `movefocus r` and `movefocus d` would be equivalent to `cyclenext ""`

(and the same for `swapnext`)

**Comment by vaxerski** [comment]
not a bug

**Comment by Narice** [comment]
Oh, woaw, I was having the same issue, but didn't know it was cycling, I thought it was random.
I was planning on using fullscreen 1 on a set of 8 windows and switching between them like usual, but I guess that's not what it was created for.
![image](https://user-images.githubusercontent.com/31109099/208005264-c2e6ca2f-0361-4f9d-8332-162d0c0e3961.png)

for context, I'm using qutebrowser-profile, so I have a bunch of seperate browsers for different tasks that I keep in the same workspace.
On i3, I would tab everything.

I know about the group function on the dwindle layout, but it is not really enough for my use case.
What's missing for me is the ability to reorder nodes that are grouped.
Being able to extract a window when having a group as the only node on a workspace would be a nice thing to have as well, but not as important. Right now you need to degroup, move the window that you are interested in as the top node, and regroup everything else.

I've also seen inconsistencies with groups when having mutiple groups on a workspace.
The togglegroup dispatcher doesn't toggle the groups anymore, but instead merges(?) the two groups:
![image](https://user-images.githubusercontent.com/31109099/208008268-4c74eb14-0a89-4d40-bbf3-7c81f14f3e9f.png)
![image](https://user-images.githubusercontent.com/31109099/208007345-f827eda2-f215-4f6e-aa6e-6d73ac74dafc.png)

Looking quickly at the code, I would say that actually one group links as it's next group member the other group (as a whole), which probably isn't intended (could be cool though if handled). That is probably why the group bar is not present on the previous screenshot.
https://github.com/hyprwm/Hyprland/blob/20899b597e8b9f16dc3f311fb8d1b8f340ea8ef8/src/layout/DwindleLayout.hpp#L22

Also, when degrouping, it doesn't restore the previous split state, switches some windows around and doesn't respect the dwindle force_split config, nor the cursor position:
![image](https://user-images.githubusercontent.com/31109099/208009301-9cd142a7-c437-4eeb-98d2-782eac183eeb.png)
![image](https://user-images.githubusercontent.com/31109099/208009565-1c64f7ba-a466-40b8-80b4-f0bfc6b32f86.png)
![image](https://user-images.githubusercontent.com/31109099/208009379-410813a3-068c-405b-8865-cd939318aee2.png)

So I basically wanted to use the fullcreen maximize as a crutch instead of solving the issue in the code (which looks daunting). I would basically have had 80% of what's cool with i3 tabs with faster navigation, the 20% lacking would have been the ability to have multiple tab groups on a single workspace.

Woaw, that came out really long, sorry about that, and I can open seperate issues for everything, I didn't know beforehand that I would write about all the issues that I encountered thus far with groups.
I'll also look a bit more at the code in case I can find myself where to fix these issues, but I don't really know how to develop and test Hyprland so that's going to be a bit of a journey x)

**Comment by swaroopanand10** [comment]
> Oh, woaw, I was having the same issue, but didn't know it was cycling, I thought it was random. I was planning on using fullscreen 1 on a set of 8 windows and switching between them like usual, but I guess that's not what it was created for. ![image](https://user-images.githubusercontent.com/31109099/208005264-c2e6ca2f-0361-4f9d-8332-162d0c0e3961.png)
> 
> for context, I'm using qutebrowser-profile, so I have a bunch of seperate browsers for different tasks that I keep in the same workspace. On i3, I would tab everything.
> 
> I know about the group function on the dwindle layout, but it is not really enough for my use case. What's missing for me is the ability to reorder nodes that are grouped. Being able to extract a window when having a group as the only node on a workspace would be a nice thing to have as well, but not as important. Right now you need to degroup, move the window that you are interested in as the top node, and regroup everything else.
> 
> I've also seen inconsistencies with groups when having mutiple groups on a workspace. The togglegroup dispatcher doesn't toggle the groups anymore, but instead merges(?) the two groups: ![image](https://user-images.githubusercontent.com/31109099/208008268-4c74eb14-0a89-4d40-bbf3-7c81f14f3e9f.png) ![image](https://user-images.githubusercontent.com/31109099/208007345-f827eda2-f215-4f6e-aa6e-6d73ac74dafc.png)
> 
> Looking quickly at the code, I would say that actually one group links as it's next group member the other group (as a whole), which probably isn't intended (could be cool though if handled). That is probably why the group bar is not present on the previous screenshot.
> 
> https://github.com/hyprwm/Hyprland/blob/20899b597e8b9f16dc3f311fb8d1b8f340ea8ef8/src/layout/DwindleLayout.hpp#L22
> 
> Also, when degrouping, it doesn't restore the previous split state, switches some windows around and doesn't respect the dwindle force_split config, nor the cursor position: ![image](https://user-images.githubusercontent.com/31109099/208009301-9cd142a7-c437-4eeb-98d2-782eac183eeb.png) ![image](https://user-images.githubusercontent.com/31109099/208009565-1c64f7ba-a466-40b8-80b4-f0bfc6b32f86.png) ![image](https://user-images.githubusercontent.com/31109099/208009379-410813a3-068c-405b-8865-cd939318aee2.png)
> 
> So I basically wanted to use the fullcreen maximize as a crutch instead of solving the issue in the code (which looks daunting). I would basically have had 80% of what's cool with i3 tabs with faster navigation, the 20% lacking would have been the ability to have multiple tab groups on a single workspace.
> 
> Woaw, that came out really long, sorry about that, and I can open seperate issues for everything, I didn't know beforehand that I would write about all the issues that I encountered thus far with groups. I'll also look a bit more at the code in case I can find myself where to fix these issues, but I don't really know how to develop and test Hyprland so that's going to be a bit of a journey x)

hey I faced the same issue, did you found a solution or workaround to it yet???
