### ISSUE TITLE
Firefox & Thunderbird crashing

### ISSUE THREAD

**Issue by ShabirK21** [hyprwm/Hyprland#1369]
They crash when using the fedora repo packages with segmentation fault, but the flatpak versions work. In gnome both repo & flatpak versions work.

**Comment by MonstrousOgre** [comment]
Nvidia card? The Nvidia page of Hyprland's wiki (and the Arch wiki too) mentions adding these two lines, but I had to comment them to get Firefox and Thunderbird working
```
export GBM_BACKEND=nvidia-drm
export __GLX_VENDOR_LIBRARY_NAME=nvidia
```
I also noticed better performance after commenting these lines

**Comment by ShabirK21** [comment]
Yeah Nvidia, always the culprit. I'll try that out later, thanks. Though any disadvantages to removing them? Im actually using a AMD & Nvidia Optimus laptop

**Comment by MonstrousOgre** [comment]
I'm not fully sure myself either. The Arch wiki explains [what those lines do](https://wiki.archlinux.org/title/wayland#Requirements). They force GBM as a backend. But I'm not sure if it uses GBM without those lines.

I also read somewhere that wlroots doesn't support EGLStreams, which means Hyprland must be using GBM regardless.

**Comment by ShabirK21** [comment]
Removing the two variables fixed. Thanks

**Comment by bratfizyk** [comment]
Hi,
Let me leave my comment here in order to - hopefully - save somebody some tears.
I had a problem with Thunderbird crashing on my machine.
In my case installing a notification deamon helped. Looks like thunderbird desperately needs something like this.
I installed `dunst`, but I guess pretty much anything would solve the problem.
