### ISSUE TITLE
activeworkspace IPC/hyprctl command

### ISSUE THREAD

**Issue by yavko** [hyprwm/Hyprland#1442]
Yes I know this is quite easy to replicate, but it would be more concise and probably more performant if it was built in to the compositor!

**Comment by leg7** [comment]
`hyprctl -j monitors | jq .[0].activeWorkspace.id`
 
If you are using only 1 monitor. It would be nice to have this be a hyprctl command because having to call jq multiple times when you have multiple monitors is very heavy. For example this is what it looks like with 2 monitors.

```
if [ $(hyprctl -j monitors | jq .[0].focused) = "true" ]; then
	hyprctl -j monitors | jq .[0].activeWorkspace.id)
else
	hyprctl -j monitors | jq .[1].activeWorkspace.id)
fi
```

The more monitors you have the more you have to pipe into jq and that is painfully resource intensive and slow.

**Comment by yavko** [comment]
Yeah thats how I have it implemented with Hyprland-rs

**Comment by leg7** [comment]
After messing more with jq I found a way faster command 

`hyprctl -j monitors | jq '.[] | select(.focused == true) | .activeWorkspace.id'`
