### ISSUE TITLE
Damage tracking incorrect on a gtk popup in evince

### ISSUE THREAD

**Issue by q234rty** [hyprwm/Hyprland#1455]
Steps to reproduce:
1. Install evince.
2. Open a document with evince.
3. Open the burger menu.
4.  Move the mouse over the burger menu and observe this:
![Strange menu](https://user-images.githubusercontent.com/11485439/215519608-6b8921c8-1253-43d4-b530-8f23c854b658.png)

**Comment by romanstingler** [comment]
@q234rty does this still happen on 44.2 and the latest git it looks good to me 
![image](https://github.com/hyprwm/Hyprland/assets/5576250/84e13495-9c7a-4f69-b635-7c159ddec20a)

**Comment by q234rty** [comment]
@romanstingler Try opening another app, make evince floating, then shrink it's window until the popup no longer fits in the window.

**Comment by romanstingler** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/5576250/72f8aa15-0078-497e-af1a-176c80e9a934)
![image](https://github.com/hyprwm/Hyprland/assets/5576250/0363a029-6623-471a-bc91-3aa39ab607f5)
![image](https://github.com/hyprwm/Hyprland/assets/5576250/62f250d4-8288-46fb-83f8-dfa962e2c7f4)

Ahh when you use floating window, I see

**Comment by Narcha** [comment]
A similar issue occurs when right-clicking to open a context menu in Gnome Files: When clicking in a position where the dialog cannot be positioned below and to the right of the cursor (for example, close to the bottom screen edge), two popups appear: The "real" one and a flickering leftover dialog, I'm guessing due to incorrect damage tracking as well. Unfortunately the visual bug disappears when taking a screenshot, so I'm unable to share an image of this happening.

**Comment by romanstingler** [comment]
@vaxerski any clue why the popup stops in the middle of the screen and starts to get squashed? 
![image](https://github.com/hyprwm/Hyprland/assets/5576250/62c0fd00-0a63-4d44-b34d-b57d2331eb8b)

**Comment by vaxerski** [comment]
only reason for this could be that it's not a popup but a subsurface in which case whoever wrote this is braindead

**Comment by izmyname** [comment]
Still actual?

**Comment by Narcha** [comment]
I just checked, and I cannot reproduce the [symptom in Gnome Files (Nautilus)](https://github.com/hyprwm/Hyprland/issues/1455#issuecomment-1651191907) anymore
