### ISSUE TITLE
Feature: 4-arguments gaps

### ISSUE THREAD

**Issue by fedoranvar** [hyprwm/Hyprland#148]
Good day to you!

Suggesting for settings gaps for each side, so
```bash
general {
...
    gaps_in=<top> <right> <bottom> <left>
    gaps_out=<top> <right> <bottom> <left> 
}
```

Thank you!

**Comment by fedoranvar** [comment]
to eliminate gap between workspace and `waybar` , but keep other gaps

![image](https://user-images.githubusercontent.com/52028706/171374754-632bb3b4-527e-40da-846b-2c116d68aae6.png)

**Comment by vaxerski** [comment]
oh

**Comment by vaxerski** [comment]
implementing this would be a bit of a pain. Can't u use custom reserved area with negative values, if you just want to make the gap smaller between the bar and windows?

**Comment by notusknot** [comment]
Any updates or workarounds to this?

**Comment by vaxerski** [comment]
if you want a to make space for a bar, use custom reserved area (see configuring monitors)

**Comment by vaxerski** [comment]
I am going to close this.

No plans to add that. For outside gaps, you can use custom reserved area. For inner gaps, this would not make sense.

Additionally, pain to parse.

**Comment by alexjp** [comment]
> but why?

I am just starting with hyprland today, trying to port my sway config to it, and loving it!

I am getting into a roadblock, which is this: I have two "2k" monitors side by side:

- in sway i have a script that, if there is only 1 window in the workspace, it adds an side edge ( on the left in the left monitor, on the right on the right monitor ).

From my understanding, I "almost" can simulate the workflow with this script listening to the socket:
```
if [[ $COMMAND = "focusedmon" ]] || [[ $COMMAND = "openwindow" ]] || [[ $COMMAND = "closewindow" ]] || [[ $COMMAND = "workspace" ]];
 then
        if [ $(hyprctl activeworkspace -j | jq -r '.monitor') == "DP-1" ]; then
            echo "DP-1"
            if [ $(hyprctl activeworkspace -j | jq -r '.windows') == 1 ]; then
                hyprctl keyword monitor DP-1,addreserved,0,0,960,0
            else
                hyprctl keyword monitor DP-1,addreserved,0,0,0,0
            fi
        else
            echo "DP-2"
            if [ $(hyprctl activeworkspace -j | jq -r '.windows') == 1 ]; then
                hyprctl keyword monitor DP-2,addreserved,0,0,0,960
            else
                hyprctl keyword monitor DP-2,addreserved,0,0,0,0
            fi
        fi
    fi
```

The issue, is of course, instead of only affecting the workspace in question, it messes all the workspaces in that monitor.

Thank you for hyprland !!!

**Comment by alexjp** [comment]
@vaxerski , Sorry for the ping, in case if my comment was not read. ( as this is a closed feature, I dont know if you have read it ).

Do you feel the "usecase" I presented is warranted to develop this feature? In case not, truly sorry for the annoyance and congrats on the amazing work!

**Comment by alexjp** [comment]
> you can listen to workspace change events too and adjust accordingly...?

thank you for replying ! you mean adjust accordingly the "addreserved" option like in the little script I presented ? That almost works, but when changing workspaces the windows all move around (because it applied to the monitor, all workspaces are changed. when moving to another workspace, the windows move to go to the proper place) (ex: if I am on a workspace with just 1 window and move to another that has 2, its visible the animation of that workspace with 2 windows adjusting the addreserved space to its proper size and vice versa when changing back to a workspace with just 1 window).

using side gaps is what I use in sway and it works well.

sorry if I misunderstood and the above isn't what you were talking about.

**Comment by vaxerski** [comment]
I don't think this will be planned any time soon, but you can make a mr.

**Comment by SwimmingPolar** [comment]
Assuming anyone's monitor configs are as following:

```
# .../hypr/monitors.conf
monitor=DP-2, 1920x1080@143, 0x0, 1
monitor=DP-1, 1920x1080@143, 1920x0, 1

# .../hypr/userprefs.conf (anyfile will do if within hypr scope)
monitor=DP-2,addreserved,-7,0,0,0
monitor=DP-1,addreserved,-7,0,0,0

# monitor=name,addreserved,TOP,BOTTOM,LEFT,RIGHT
```
The negative margin may differ but I'm good with that.
Just in case anyone's interested in balancing the top and bottom margin.
