### ISSUE TITLE
lockscreen: crash after wakeup 

### ISSUE THREAD

**Issue by primalmotion** [hyprwm/Hyprland#1519]
- clamshell mode (laptop screen disabled)
- start lockscreen
- suspend
- wake up
- swaylock is stuck and unresponsive
- open lid to reenable laptop monitor
- red screen for a few sec
- crash

```

                Stack trace of thread 402339:
                #0  0x00007fcd55c8b74d wlr_addon_find (libwlroots.so.12032 + 0xa074d)
                #1  0x00007fcd55c95299 wlr_xwayland_surface_try_from_wlr_surface (libwlroots.so.12032 + 0xaa299)
                #2  0x0000559e924bbdf5 _ZN20CHyprXWaylandManager15activateSurfaceEP11wlr_surfaceb (Hyprland + 0x100df5)
                #3  0x0000559e923fe6fe _ZN11CCompositor12focusSurfaceEP11wlr_surfaceP7CWindow (Hyprland + 0x436fe)
                #4  0x0000559e924ba1d0 _ZL16handleSurfaceMapPvS_ (Hyprland + 0xff1d0)
                #5  0x0000559e9248bb0c _Z13handleWrappedP11wl_listenerPv (Hyprland + 0xd0b0c)
                #6  0x00007fcd55af2f6e wl_signal_emit_mutable (libwayland-server.so.0 + 0x9f6e)
                #7  0x00007fcd55c68a0b surface_commit_state (libwlroots.so.12032 + 0x7da0b)
                #8  0x00007fcd54f594f6 n/a (libffi.so.8 + 0x74f6)
                #9  0x00007fcd54f55f5e n/a (libffi.so.8 + 0x3f5e)
                #10 0x00007fcd54f58b73 ffi_call (libffi.so.8 + 0x6b73)
                #11 0x00007fcd55af1ada n/a (libwayland-server.so.0 + 0x8ada)
                #12 0x00007fcd55af601c n/a (libwayland-server.so.0 + 0xd01c)
                #13 0x00007fcd55af49e2 wl_event_loop_dispatch (libwayland-server.so.0 + 0xb9e2)
                #14 0x00007fcd55af5197 wl_display_run (libwayland-server.so.0 + 0xc197)
                #15 0x0000559e923f142d main (Hyprland + 0x3642d)
                #16 0x00007fcd55354790 n/a (libc.so.6 + 0x23790)
                #17 0x00007fcd5535484a __libc_start_main (libc.so.6 + 0x2384a)
                #18 0x0000559e923faf35 _start (Hyprland + 0x3ff35)
```

**Comment by jmgisele** [comment]
same issue! i've been debugging for ~2-3 days straight no luck. suspend works fine, but with swaylock, I have to get into a tty and restart the display manager to get anywhere.

**Comment by jmgisele** [comment]
Hi! Found a complicated workaround. Here's what I've found in my time debugging. Note I'm on both an AMD CPU and a NVIDIA card which both have some suspend issues (woo!):
- Activating swaylock on suspend or sleep events via a systemd hook in `/etc/systemd/system/` does not work. Swaylock does activate, but as per above, it's completely frozen. On `WantedBy=suspend.target` and `Before=suspend.target`, you can get to a tty and restart the display manager and then login as usual. With `WantedBy=sleep.target` and `Before=sleep.target`, the whole machine crashes (Hyprland "dumps core" in journald).
- Generally there are no scary messages in journald when this happens, things just fail silently
- Spent hours fidgeting with `nvidia-sleep.service`, `nvidia-resume.service`, `/proc/driver/nvidia/params` via `/etc/modprobe.d` modules etc. to no avail. Suspend was working before earlier this week, so I don't think it's an issue with those settings.
- Disabling the systemd service hook and activating swaylock, THEN suspending/sleeping DOES work. EG: I execute `swaylock` from kitty, close my laptop lid, open it back up again and I can unlock as usual, no freezing
- Obviously that's....not ideal. I do not want to manually open a terminal and execute a command every time i want to close my laptop or leave it for a bit. So I found a workaround:

WORKAROUND:
I managed to find a manual fix using [acpid](https://wiki.archlinux.org/title/Acpid) and [user-acpid](https://gitlab.com/jokeyrhyme/user-acpid-rs) for locking upon lid close:
- Install and enable `acpid` and `user-acpid`; the latter is needed because we need access to our display environment in order to specify which display swaylock should appear on.
  - `systemctl enable --now acpid.service`
  - `systemctl enable --user --now user-acpid.service`
  - check via `systemctl status` to make sure they're both running
  - In `~/.config/user-acpid`, create an executable file called button-lid-close with contents:
  ```
	#!/bin/zsh
	DISPLAY=:1 swaylock
  ```
	- or whatever your preferred shell is (bash etc). make sure `DISPLAY` is set to whatever the output of `echo $DISPLAY` returns
	- reboot to make sure everything's set up correctly
	- should be good!

**Comment by vaxerski** [comment]
Well it would help if I could repro it. I use swaylock on my lappy and it's a-ok.

Does it also happen if you don't suspend? Just lock, and open laptop

**Comment by primalmotion** [comment]
yes, even without suspend. Also I don't use nvidia

- laptop monitor is disabled (only the external display is on)
- lock screen
- open lid
- flip a coin
- tails: you get a temporary red screen, but swaylock comes back and it's ok
- heads: you get  temporary red screen, then it crashes

**Comment by primalmotion** [comment]
also my monitor is scaled at 1.30 (as it already happened to be a source of bugs)

**Comment by primalmotion** [comment]
this one really makes my life miserable lol

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/10715850/patch.txt)

try this patch

**Comment by primalmotion** [comment]
yeah, that seems to fix the crash.

**Comment by primalmotion** [comment]
not sure if this is Hyprland fault or not, but while it does not crash anymore, most of the time my external keyboard does not input anything in swaylock, until I open the lid (then the kb works). If I close the lid again, kb stops working until I reopen it.

**Comment by vaxerski** [comment]
fixed the crash then

**Comment by primalmotion** [comment]
want me to open another issue for the focus (I think?) issue?

**Comment by vaxerski** [comment]
feel free, but first check on swae

**Comment by mooncoffee1** [comment]
i downgraded hyprland, works now, soo its hyprland error or smth, idk.

**Comment by MightyPlaza** [comment]
if you think so then bisect it
