### ISSUE TITLE
Rofi loses focus on the new version

### ISSUE THREAD

**Issue by GrenicMars** [hyprwm/Hyprland#1619]
Today i updated hyprland and i can't select items inside a rofi menu anymore, the rofi window doesn't focus when i open it, and i can't press <kbd>ESC</kbd> to quit rofi. I know rofi doesn't have native wayland support and it runs on xwayland, but it works just fine like on Xorg before i updated. This problem happened before when i use hyprland git version. I use arch linux and install hyprland stable version by aur, and i use rofi git version which is also installed by aur.
## System information
* Distro: arch linux
## Version
* Hyprland:
```
$ pacman -Q --info hyprland | head -n 2
Name            : hyprland
Version         : 0.22.0beta-1
```
* Rofi:
```
$ pacman -Q --info rofi | head -n 2
Name            : rofi-git
Version         : 1.7.5.r116.gf6248c6e-1
```
## Steps to reproduce
install rofi (doesn't work on rofi stable version neither) and open it.
## Expected behavior:
rofi works the same way as i run it on xorg.

**Comment by vaxerski** [comment]
already fixed in HEAD, consider updating or not using x11 rofi

**Comment by lchanmann** [comment]
@vaxerski  I didn't know whether to create an issue or not but I updated hyprland today and has been experiencing rofi window not having focus and have to move mouse over the window to be able to use it.

## System information
- Distro: Arch linux

## Version
- Hyprland:

```
$ pacman -Q --info hyprland | head -n 2
Name            : hyprland
Version         : 0.37.1-1
```

- Rofi:

```
$ pacman -Q --info rofi | head -n 2
Name            : rofi
Version         : 1.7.5-2
```

## Steps to reproduce

install rofi and open it.

## Expected behavior:

rofi window should have focus upon opening.

**Comment by vaxerski** [comment]
instead of pinging use the search feature. #5142
