### ISSUE TITLE
Albert launcher looses focus on input

### ISSUE THREAD

**Issue by DomLankutis** [hyprwm/Hyprland#1630]
When launching albert, after any key input the floating window resizes causing it to lose focus and close.

How can I ensure that the focus is kept of the launcher?

EDIT: Managed to fix the issue by setting windowrulev2, forceinput and windowdance

**Comment by vaxerski** [comment]
> Managed to fix the issue by setting windowrulev2, forceinput and windowdance

closing then. If it's a launcher it should not be a window anyways.

**Comment by savannidgerinel** [comment]
I'd actually like to reopen this. Quick Access in 1Password, and potentially other password managers, is all about quickly accessing items without going into the full app. We open a floating window for that and the window gets automatically resized while it's open.

What I'm seeing is that a window resize event immediately causes a blur event unless I happen to have moved my mouse cursor over where the Quick Access window happens to be, whereas on Sway that blur event doesn't occur.

**Comment by vaxerski** [comment]
? I don't understand your issue

**Comment by savannidgerinel** [comment]
Sure, a video will actually be helpful here. In this video, I have 1Password open. Not visible here is that I hit a keybinding that opens Quick Access, a secondary window of 1Password (bind = $mainMod, Q, exec, oph --quick-access).

1. The Quick Access window has focus.
2. I type a letter to begin searching.
3. Quick Access changes size to show the search results.
4. Hyprland only: Something triggers a blur event. (this is the step that doesn't happen on Sway or Gnome)
5. Focus lands back where the mouse was, in this case on the terminal. Keyboard input is now going to the terminal instead of to Quick Access.

https://github.com/hyprwm/Hyprland/assets/8534888/acb5ecaa-076a-4412-b9c1-8339884844b2

I've set up some rules in my `hyprland.conf`:

```
input {
    ...
    follow_mouse = 0
    mouse_refocus = false
    ...
}

windowrule = forceinput, ^(Rapida Atingo — 1Password)$
```

And this is the Quick Access window from `hyprctl clients`:

```
Window 3ec4480 -> Rapida Atingo — 1Password:
	mapped: 1
	hidden: 0
	at: 2925,666
	size: 550,188
	workspace: 3 (3)
	floating: 1
	monitor: 1
	class: Electron
	title: Rapida Atingo — 1Password
	initialClass: Electron
	initialTitle: Rapida Atingo — 1Password
	pid: 328992
	xwayland: 1
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0
```

The desired behavior is that a resize does not trigger a blur event.

**Comment by vaxerski** [comment]
okay, I get it now... Why the heck are you calling it a blur event? tf is a blur event?

**Comment by vaxerski** [comment]
at any rate, doesn't the `stayfocused` windowrule fix that?
