### ISSUE TITLE
Hyprland crash (middle of session, while the thing was idling)

### ISSUE THREAD

**Issue by frigaut** [hyprwm/Hyprland#171]
Rather long session, was reconnecting to wifi with nm-applet, and the session froze. 
after waiting for a few seconds, tried to switch to tty. Eventually, hyprdland or wlroots crashed. 
Attached picture of tty, hyprland log and coredump.

![20220608_143544](https://user-images.githubusercontent.com/613346/172621191-547423a6-a331-4774-a349-b896f1b38b5e.jpg)
[hyprland.log](https://github.com/vaxerski/Hyprland/files/8861653/hyprland.log)
[hyprland.core.txt](https://github.com/vaxerski/Hyprland/files/8861657/hyprland.core.txt)

**Comment by vaxerski** [comment]
![image](https://user-images.githubusercontent.com/43317083/172624670-6f2d5f3a-3958-417d-985b-2cbc5e1fc65f.png)

?

TTY switching will most likely freeze the entire PC and it's an issue that i've reported here:
[https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3447](https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3447)

No clue whether it's an issue with hyprland or not, but wayland's core is not behaving the way i'd expect it to. That's the root cause of TTY switches and freezes.

Can you maybe pinpoint where the compositor froze?

The crash you got was fixed, but it was generally caused by the last monitor being destroyed. (Either unplugged or just wlroots died)

**Comment by frigaut** [comment]
I'll try. 
When I found it frozen, there was a tooltip opened that I had never seen before, something about the network I was on which seemed emanated from the floating gtk-layer-shell window (nm-applet stuff that you bring from the tray nm-applet). Perhaps has to do with this. I'll keep updating this bug if I see anything that seems related.

**Comment by frigaut** [comment]
no repeat, closing this issue.
