### ISSUE TITLE
super key on virutal machines

### ISSUE THREAD

**Issue by snowy-shadow** [hyprwm/Hyprland#1713]
This is 1/2 bug and 1/2 feature request. Can you set the keybinding for kitty and exit on the default configuration to not use the <SUPER> key? Currently I cannot do anything because I can't open the terminal. 
I am running linux in vmware and the super key gets intercepted by the host, so it is not possible to press the super key. This seems to be a wayland issue. 

See similar issues here:
https://gitlab.gnome.org/GNOME/gnome-boxes/-/issues/881
https://askubuntu.com/questions/1013214/vmware-workstation-14-does-not-let-me-direct-super-key-to-machine

**Comment by vaxerski** [comment]
This is not an issue with wayland per se, but your compositor grabbing the meta key.

No clue why this is an issue though, if you can't use meta then go into the config before launching hyprland and edit the keybinds...?

If you are using hyprland as a host, you can create an empty submap with only a keybind to exit it in order to pass everything into a vm. It's described on the wiki.
