### ISSUE TITLE
Wayland windows created on 100% scale doesn't scale on it's own to 200%

### ISSUE THREAD

**Issue by grappas** [hyprwm/Hyprland#1794]
https://cdn.discordapp.com/attachments/995047159542063154/1085673198827356210/2023-03-15_21-49-35.mkv

^^^ note when I grab window with mouse and put back it sharpens.

Steps to reproduce:
1. Have two monitors with different scaling.
2. Create window on lower scaled monitor.
3. Use shortcut (movewindow, movetoworkspace) to higher dpi monitor.

Expected behaviour:
Window is rescaled to 200%

Noted outcome:
Window is blurry like a xwayland app. It rescales only when is dragged with mouse. Window created in higher dpi monitor isn't affected.

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/10985548/patch.txt)

can you check this

**Comment by grappas** [comment]
> 

do you mean compile recent git repo?

**Comment by fberg** [comment]
I think I'm running into the same bug with Alacritty, see https://github.com/alacritty/alacritty/issues/6973. (Also happens if the scales are 1.0 and 2.0 as in the OP.)

Moving the window with the mouse works as expected, but `movecurrentworkspacetomonitor` using a keyboard shortcuts leads to blurry fonts. Changing the scale on the monitor with the terminal window (by editing the config file) also has the same effect.

This is on Hyprland 0.25.0 and also on the newest revision (9cf72a30fc040f0bd2fb4651ec7f8e82df962278).
