### ISSUE TITLE
hyprland crashes when closing laptop lid

### ISSUE THREAD

**Issue by hexisXz** [hyprwm/Hyprland#1887]
so i installed hyprland a few days ago. i now have it configured to my liking so i closed the lid and went to do something else and when i came back to my laptop hyprland crashed no wallpaper no bar and i cant restart the bar or wallpaper, i have to reboot every time. it wasn't that one time either its every time i close the lid.

**Comment by vaxerski** [comment]
not having a bar is not hyprland crashing. Hyprland crashing is when you get booted back to your login manager / tty.

What do you mean by "can't restart bar"

Have you tried opening a terminal and launching your bar and wallpaper?

**Comment by hexisXz** [comment]
> not having a bar is not hyprland crashing. Hyprland crashing is when you get booted back to your login manager / tty.
> 
> What do you mean by "can't restart bar"
> 
> Have you tried opening a terminal and launching your bar and wallpaper daemon?

no no i mean like half of hyprland doesn't function like for example i have a panel that pops out when i put my mouse to the left side of the screen stuff like that doesn't work. and i did try launching the bar and wallpaper daemon but they don't popup. but i really dont know whats wrong here

**Comment by vaxerski** [comment]
they might still be running, but be in a limbo.

Some laptops, yours included it seems, physically disconnect the display on lid close. Hyprland reacts accordingly by telling the layers that they got closed (monitor got removed)

some apps might malfunction with no displays.

Try killing them (maybe they are still running) and then starting again.

**Comment by hexisXz** [comment]
> 

i did that they wont run until i restart same with the wallpaper

**Comment by vaxerski** [comment]
odd, no clue. I assume normal windows open.

Never seen this.

**Comment by hexisXz** [comment]
> odd, no clue. I assume normal windows open.
> 
> Never seen this.

yeah, windows open but everything crashes and the wallpaper goes grey so idk whats going on

**Comment by hexisXz** [comment]
okay so i typed sudo systemctl suspend and everything works fine when i open the lid but its only when i close the lid everything stops working

**Comment by Froggo8311** [comment]
What's in your hyprland config? Maybe something in there is causing that- I've never experienced anything similar.

**Comment by hexisXz** [comment]
> What's in your hyprland config? Maybe something in there is causing that- I've never experienced anything similar.

well... i am using https://github.com/AmadeusWM/dotfiles-hyprland.git

**Comment by Froggo8311** [comment]
Looks like this might have something to do with it (found in `keybinds/default.conf`):
```conf
bindl=,switch:off:Lid Switch,exec,hyprctl keyword monitor "eDP-1, 2560x1600, 0x0, 1"

bindl=,switch:on:Lid Switch,exec,hyprctl keyword monitor "eDP-1, disable"
```

**Comment by hexisXz** [comment]
> Looks like this might have something to do with it (found in `keybinds/default.conf`):
> 
> ```
> bindl=,switch:off:Lid Switch,exec,hyprctl keyword monitor "eDP-1, 2560x1600, 0x0, 1"
> 
> bindl=,switch:on:Lid Switch,exec,hyprctl keyword monitor "eDP-1, disable"
> ```

okay, so do i comment them out?

**Comment by ConfusedAlex** [comment]
I have the same issue. I also have this in my config so I can use my laptop with a docking station.

```
bindl=,switch:off:Lid Switch,exec,hyprctl keyword monitor "eDP-1, 2560x1600, 0x0, 1"
bindl=,switch:on:Lid Switch,exec,hyprctl keyword monitor "eDP-1, disable"
```

Using an external monitor everything works as expected. But if I dont have a external monitor connected, waybar and swww stop displaying what they should displaying.

**Comment by jakubkaczor** [comment]
I have the exact same issue. Having these options is needed in order to, for example, move the workspaces to the remaining monitor after closing the lid, but unfortunately, it results in a malfunction when there is no display enabled.

I would say that, as vaxerski said, some programs may behave improperly when there is no display, but I also noticed that closing and opening the lid one more time results in windows, tried to be opened using standard hyprland key maps, don't get displayed. The key maps work, as I confirmed setting one logging, but the windows don't get displayed. Perhaps the issue should be reopened, shouldn't it?

**Comment by Mooninghnk** [comment]
this is not hyper related btw. try editing `/etc/systemd/login.conf` 
find `#HandleLidSwitch=suspend` change it to ` HandleLidSwitch=ignore`, and uncomment it that did the trick for me. What happens is when you do close the lid, laptop will be put to sleep preventing u from using it. With this config we ignore the lid close. my monitor settings in `monitor = HDMI-A-1, preferred,auto,1,mirror,eDP-1` and my binds: 
`bindl = , switch:off:Lid Switch,exec,hyprctl keyword monitor "eDP-1, 1920x1080@120, 0x0, 1"`

`bindl = , switch:on:Lid Switch,exec,hyprctl keyword monitor "eDP-1, disable"`

these binds should handle the lid close and disable the screen
and our login.conf should handle the lidswtch to ignore it instead of suspending it

LMk if this helps !!

**Comment by jakubkaczor** [comment]
Now your device isn't put to sleep on lid closed, but I would like to preserve it. You say that this is not Hyprland related, but don't you expect Hyprland handle the case of systemd putting to sleep, and closing the lid?
