### ISSUE TITLE
White flickering on the right side of the screen with Chromium

### ISSUE THREAD

**Issue by LDAP** [hyprwm/Hyprland#1899]
## Steps to reproduce

1. Open Chromium
2. Watch a video 
3. Switch to another workspace
4. Switch back

## Expected outcome
Nothing on the right side of the screen

## Noted outcome
White flickering on the right side of the screen.

- Toggling full screen fixes it temporarily
- Trying to take a screenshot fixes it temporarily :(

Hyprland: e994b0c8b881de5145e583720abbd9ff27d727ac

```
Monitor eDP-1 (ID 0):
	2560x1440@59.998001 at 0x0
	description: LG Display 0x058B (eDP-1)
	make: LG Display
	model: 0x058B
	serial:
	active workspace: 1 (1)
	reserved: 0 40 0 0
	scale: 1.50
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: 0
```

**Comment by vaxerski** [comment]
video please?

config?

nvidia?

**Comment by LDAP** [comment]
> video please?

Using wf-recorder fixes is temporarily. Here is a video I took with my phone:

https://user-images.githubusercontent.com/8215084/228156256-20099cd0-1005-4913-b176-4f7bdc6c1794.mp4


> config?

[config.tar.gz](https://github.com/hyprwm/Hyprland/files/11086414/config.tar.gz)

 
> nvidia?

No.

**Comment by NomisIV** [comment]
I might have this problem too, and I think it's related to the 1.5 scaling factor. When a window is in fullscreen, or otherwise draws "off of the edge" on the right side (like animations when switching workspaces), it's not resetted by hyprland. I even had this problem on sway.

**Comment by LachlanS7** [comment]
I am having this problem too. It seems to be an issue with scaling and not exclusive to Chromium. It can even happen when the scale factor perfectly divides both the width and height of the monitor. 

From the little testing I have done, it appears to be dragging over some pixels from the previous workspace onto the new workspace and not updating them until they are required to be redrawn (the problem persists only with damage_tracking = 2). Finally, when there is no transition animation, this problem is fixed.

**Comment by MightyPlaza** [comment]
still happening?

**Comment by VixieTSQ** [comment]
> still happening?

This is fixed for me.
