### ISSUE TITLE
How to switch focus to previous window in the same workspace?

### ISSUE THREAD

**Issue by TTtrace** [hyprwm/Hyprland#2061]
### Discussed in https://github.com/hyprwm/Hyprland/discussions/2037

<div type='discussions-op-text'>

<sup>Originally posted by **TTtrace** April 13, 2023</sup>
The `focuscurrentorlast` dispatcher will move focus to the previously focused window, no matter in which workspace. 

I hope to use `ALT + Tab` to switch focus between two windows in the same workspace, how to achieve that?

Further more, if we type `ALT + Tab ` once, focus will cycle through just two window in the workspace; if we type `ALT + Tab ` many times, focus can cycle through all the windows in the workspace. This behavior looks like in Windows/macOS. Is this possible?</div>

**Comment by tchofy** [comment]
bind = ALT,Tab,cyclenext

And if you happen to have two or more floating windows overlapping, you might also want to add a second bind to the same keys:
bind = ALT,Tab,bringactivetotop

**Comment by TTtrace** [comment]
> bind = ALT,Tab,cyclenext prev

I have tried it. Unfortunately not what I expect. 

Let me make it clearer. The Scenario is: 

There are three or more windows in the same workspace. I do something in window 1, and move to window 2 for something else. Then if I want to go back to window 1 , I just ALT+Tab. After a while, I can switch back to window 2 using ALT + Tab. This way, ALT + Tab always makes me go back to previous focused window.

But `cyclenext, prev` will move like: window 1 -> 2 -> 3 -> 4 -> 1 ...

By the way, if windows in the workspace is in full screen mode, `cyclenext, prev` will act as I need, different from normal behavior.

Anyway, thank you for your help!

**Comment by tchofy** [comment]
Ah I see, sorry for the misunderstanding.

I mulled over this for a bit, tried binding `hyprctl dispatch cyclenext || hyprctl dispatch cyclenext prev`, like the wofi/rofi bind suggested in the wiki, but seems like it only works for processes that hang on.
Your idea is essentially the `workspace previous` dispatcher (with misc:allow_workspace_cycles 1) but for `cyclenext` instead, so each window remembers what as focused before, like workspaces remember what was the previous workspace. Would be an interesting feature to have.

**Comment by mgutz** [comment]
I asked the same Q on reddit about `master` layout and switching between last focused window. `hyprctl` doesn't return enough metadata to script solutions. To get close to this in `master` layout, bind `focuscurrentorlast` and `layoutmsg, swapwithmaster`. 

Unfortunately, there isn't enough metadata to determine if the active window is master or a slave in the layout. The solution would be simple, at least with master layout:

```
if is_focused_master:
    hyprctrl dispatch "focuscurrentorlast"
    hyprctl dispatch "layoutmsg swapwithmaster"
else:
   hyprctl dispatch "swapwithmaster"
```

In an ideal world, `hyprctl` would provide metadata about the current workspace layout, the order of clients within the layout and a MRU clients stack. Additionally, a dispatcher like `swapwindows ADDR1 ADDR2`.

I probably could take a stab at a PR, but it's been ages since I touched C++.

**Comment by valerii15298** [comment]
I use these bindings:
```
bind = ALT,Tab,cyclenext
bind = ALT_SHIFT,Tab,cyclenext,prev
```
Quite useful
ALT+TAB => to go forwards and
ALT + SHIFT + TAB => to go backwards
Similar experience to what I have with browser tabs(ctrl+tab and ctrl+shift+tab)

**Comment by aposteeltje-bwg** [comment]
Hi all.
I found this website, when i was searching for the exact same functionallity and bindings:
https://lib.rs/crates/window_switcher

**Comment by aposteeltje-bwg** [comment]
I used i3-wm for years, and it has a unique feature:
auto_back_and_forth , which is applicable to workspaces.
So, what it does is:
Say, i'm on ws.2, running a browser.
I open a terminal, which opens on ws.1 and autom. switches to ws.1., bringing the terminal on top.
Now, when i invoke "Alt-Tab"., it switches back to the previously focused window, across workspaces, so it switches to ws.2 , bringing the browser on top.

When i close the terminal on ws.1 ., the exact same thing happens, and brings me back to ws.2 ., de browser focused.

I'm looking for the same functionallity for Hyprland, and the closest thing/setting i can think of is:

(since we can bind more commands to the same binding...)
bind = ALT, Tab, cyclenext # cycle through applications on same workspace
bind = ALT, Tab, bringactivetotop # while cycling on same workspace, bring selected to top
bind = $mainMod, Tab, focuscurrentorlast # bring back focus to previous focused window across workspaces

It somehow DOES work., allthough it's not really the same.

**Comment by zvictor** [comment]
hyprswitch is the only thing that worked for me:

[hyprswitch.conf](https://github.com/user-attachments/files/16120360/hyprswitch.txt)

**Comment by izmyname** [comment]
Since the question was answered - close?

**Comment by adamnejm** [comment]
This script will switch back and forth between the 2 most recently focused window on the same workspace. Works with floating clients, special workspaces, remembers history per workspace, doesn't break when moving clients within or across workspaces.

```
#!/usr/bin/env bash

active_workspace="$(hyprctl activewindow -j | jq -r ".workspace.id")"
if [ "$active_workspace" = "null" ]; then exit; fi

previous_client="$(hyprctl clients -j | jq -r '[.[] | select(.workspace.id == '"$active_workspace"')] | sort_by(.focusHistoryID) | nth(1) | .address')"
if [ "$previous_client" = "null" ]; then exit; fi

# TODO: Replace `bringactivetotop` with `alterzorder top` after https://github.com/hyprwm/Hyprland/issues/5490 is fixed
hyprctl --batch "dispatch focuswindow address:$previous_client; dispatch bringactivetotop"
```

**Comment by aloispichler** [comment]
Now, there exists hyprswitch. There is no need for a script anymore.

**Comment by adamnejm** [comment]
Now, there exists a script. There is no need for a dependency anymore.

**Comment by Fabrice-Bernes** [comment]
Now, there exists an API. There is no need for a script anymore.
```lua
hl.bind(
    mainMod .. " + TAB",
    function()
        local cmp = function(a,b) return a.focus_history_id < b.focus_history_id end
        local windows_in_ws = hl.get_windows({workspace=hl.get_active_workspace()})
        table.sort( windows_in_ws, cmp )
        if #windows_in_ws > 1 then
            hl.dispatch ( hl.dsp.focus({ window = windows_in_ws[2]}) )
        end
    end
)
```
I don't know if there was no API before. I just started to switch and wanted a lua answer to this.
