### ISSUE TITLE
how to fix the sound problem?

### ISSUE THREAD

**Issue by ubuntu24** [hyprwm/Hyprland#2070]
Please consult the issue guidelines at
https://github.com/vaxerski/Hyprland/blob/main/docs/ISSUE_GUIDELINES.md
BEFORE submitting.

**Comment by ubuntu24** [comment]
using a physical keyboard cant adjust the loudness of the sound. thanks

**Comment by Aqa-Ib** [comment]
This is not a bug. You just have to learn how to do it. Bind the keys and the events in hyprland.conf, like this example:
`bindle=,XF86AudioRaiseVolume,exec,wpctl set-volume -l "1.0" @DEFAULT_AUDIO_SINK@ 6%+
bindle=,XF86AudioLowerVolume,exec,wpctl set-volume -l "1.0" @DEFAULT_AUDIO_SINK@ 6%-
`
Next time, you can ask this kind of questions in the _Discussions_ tab on github instead of _Issues_.

**Comment by vaxerski** [comment]
bind them, this is not kde.
