### ISSUE TITLE
Add ontop/above property for floating windows.

### ISSUE THREAD

**Issue by nferhat** [hyprwm/Hyprland#2081]
By default floating windows are *always* ontop/above other tiled windows.

Adding a toggle for this ontop state could be useful for certain workflows where you need tiled and floating windows that aren't super important.

**Comment by vaxerski** [comment]
no

**Comment by Aqa-Ib** [comment]
One utility would be to always see one program pinned behind others through transparency.

**Comment by real-fht** [comment]
> no, why

My workflow consists having a floating window for whatever program I am debugging you while the terminal I spawned it from have the logs

Another one is sometimes for games as they behave always better floating, sometimes I need to reopen steam to check stuff out but guess what it's tiled and I can't see it.

**Comment by robinmayol** [comment]
Hi, I second this. I am quite limited in screen real estate and back in AwesomeWM I used Conky to show my calendar events as a permanent widget on my desktop. When all my windows are shut I unconsciously see it and it's saved me forgetting stuff many a times. Would love to be able to do this on Hyprland. Which is "awesome" as well btw :)

**Comment by nferhat** [comment]
Closing as this is dead and probably won't get implemented at all

**Comment by ceuk** [comment]
Does anyone have a workaround or any tips for dealing with this? 

I didn't realise how often I relied on being able to switch between a floating and non-floating window until migrating from awesomewm to hyprland, it's super jarring when the tiled window stays behind the floating window (often more-or-less completely obscured) despite being active. 

The only alternative I've managed to find currently is to either:

* Unfloat the floated of the window (horrible: disrupts layout and given that I'm usually doing some kind of visual "back and forth" when this happens, that's really annoying as I often lose my place)
* Float the unfloated window (annoying: forces me to manually position 2 windows instead of just managing one)
* Move the floated window somewhere else e.g. special workspace (annoying: more complex workflow/bindings, more "state" to track in my mind/greater cognitive load)

Any suggestions based on what other people do would be great!

**Comment by ElMelchizedek** [comment]
seconding this: i find it quite funny that this feature does not already exist in hyprland

**Comment by nferhat** [comment]
> seconding this: i find it quite funny that this feature does not already exist in hyprland

To be fair its quite complicated depending how you do layouts with your compositor.

Hyprland like many others do two layers: A floating layer and a tiled layer. This approach is adopted by sway and other compositors.

Now that I have implemented my own compositor I can understand why this can be complicated
