### ISSUE TITLE
Looking for a comprehensive guide on "How to create a window manager".

### ISSUE THREAD

**Issue by MubinMuhammad** [hyprwm/Hyprland#2157]
I want to create my own window manager. I tried to follow the wiki from the wlroots library at Gitlab. But most of the information was out-dated.

So, it would be very beneficial if Hyprland team is kind enough to create a Step-By-Step guide on how to create your own WM.
By the way "tinywl" in that gitlab wlroots repo failed to compile. and showed many function errors.

So, A comprehensive guide would be very helpful, to not only me, But to others too.
Please consider it.

If you all are don't want to give much time to create one. Please give some reference, and where to get started.

**Comment by vaxerski** [comment]
No information is outdated.

Firstly, wm? You mean a wayland compositor? There are no wms in Wayland.

Firstly, it makes no sense for us to do that. It's as ridiculous as asking idk BMW to make a public tutorial on how to make your own car company with step-by-step instructions on how to build a car.

However, your request is even more ridiculous, as the source of Hyprland is 100% open. You can go read it yourself.

Building a wayland compositor is a difficult and challenging task requiring a lot of programming experience which you don't seem to have, and that's the reason why you are unable to even begin. Not a lack of a tutorial.

The fact you're not even able to compile wlroots is a good indicator you should _not_ be making your own wayland compositor due to the lack of fundamental knowledge. It's like trying to make a house without knowing how wood or bricks work.

**Comment by MubinMuhammad** [comment]
Ok, thanks for advice.
