### ISSUE TITLE
More animation options

### ISSUE THREAD

**Issue by godalming123** [hyprwm/Hyprland#236]
I would like to have different animations on window open/close. This is so that my launcher can have a scale in animation for opening and scale out for closing.
The syntax for this could look like so:
```
bezier=openAnim,0.05,0.9,0.1,1.1
bezier=ease,0.5,0,0.5,1
bezier=normal,0.5,0.5,0.5,0.5

animation=fadein,1,0.5,default
animation=windows,1,0.8,openAnim,slide

windowrule=animation popin 1,0.5 openAnim ONOPEN,launcher #this animation would only apply on open
windowrule=animation popout 1,0.5 normal ONCLOSE,launcher #this animation would only apply on close and uses a new pop animation that scales a window up

```

**Comment by CharlesEkkel** [comment]
Yeah I agree, I reckon this would be a neat change .

I'd like it because I'm personally not a huge fan of the way popin looks on closing a window, especially when it overlaps with the window which has resized to fill the gap, but it's quite lovely on open. So being able to pick different animations for each would be great.

But I'm not sure if your suggested syntax is the simplest it could be. Would it instead be possible to add some more optional parameters to the animation pragma, to give it feature parity with the full animation declarations while maintaining backwards compatibility? (plus an int to indicate whether the animation is on close or open) E.g.

`windowrule=animation STYLE OPTION SPEED CURVE WHEN, REGEX`

Where `WHEN` can be: 
- 0, [default] which indicates to apply the animation on both entry and exit.
- 1, which applies the animation only on entry
- 2, which applies it on exit.

But I have no idea how these pragmas are parsed so it might not be possible/might be needlessly complex to have an optional parameter in the middle. In which case a breaking change with more implementable syntax might be:

`windowrule=animation STYLE SPEED CURVE WHEN OPTION, REGEX`

**Comment by vaxerski** [comment]
since the recent animation config rework i'd classify this as done.
