### ISSUE TITLE
WM Completely Crashes With RuneLite For Seemingly No Reason (FAULT_PTE ACCESS_TYPE_VIRT_READ)

### ISSUE THREAD

**Issue by QueenOfDancingStars** [hyprwm/Hyprland#2408]
I've been having this problem very consistently where my Hyprland just entirely crashes when playing RuneLite. I've changed every variable possible inside the game and it is still happening, and every lead I've had has been a dead end.
I've tried disabling GPU plugins, gamescope, window options, disabling steam overlay, and not moving my mouse out of the game, and it is still happening.
After trying to check Hyprland, I've found a lot of interesting things. The error that someone pointed me to was "ENGINE GRAPHICS GPCCLIENT_PROP_0 faulted @ 0x1_007f0000. Fault is of type FAULT_PTE ACCESS_TYPE_VIRT_READ"
The same error happened about 5 times with different memory addresses at the same time.
This same error also appeared several times before this in different situations, but nothing bad seemingly happened, or was something pretty minor.
I'm not an expert at all, so I'll attach the most logs and information I can, and hope that is enough to pinpoint the issue.
I've been trying to troubleshoot this for 2 days, but frankly I am lost, and would appreciate it any help, since I am very frustrated and just want to play the game :(.

[hyprlandlogs1.txt](https://github.com/hyprwm/Hyprland/files/11619333/hyprlandlogs1.txt)
[hyprlandCrashReport158749.txt](https://github.com/hyprwm/Hyprland/files/11619326/hyprlandCrashReport158749.txt)
[hyprlandCrashReport143657.txt](https://github.com/hyprwm/Hyprland/files/11619327/hyprlandCrashReport143657.txt)
https://justpaste.it/d368b

**Comment by vaxerski** [comment]
disable direct scanout in hl config

**Comment by Pipenguim** [comment]
Might have pinned down the problem. After a while of searching, I thought it was my custom cursor, but it crashed without it.
After taking a closer look, I believe steam overlay is what is causing this problem, since the error for it happens and then the entire system crashes. Log screenshot below to show my evidence for this theory.
![image](https://github.com/hyprwm/Hyprland/assets/70240564/9d43d565-1abe-4031-8319-79c1f8b7bf60)
![image](https://github.com/hyprwm/Hyprland/assets/70240564/ae478b55-9741-4a4e-ae54-c8520a6d6ed3)
I could be wrong, but this seems like the most plausible theory after crossing out different factors. The common factor between all of the crashes was that I was running games through steam (osu, runelite, and yuzu)(Local games added to steam for properties).
Today I played runelite without using the steam shortcut and it ran fine for an entire hour, so this seems like the most plausible theory at the moment.

**Comment by izmyname** [comment]
Bump. Does it crash now?

**Comment by izmyname** [comment]
No response - prolly close?
