### ISSUE TITLE
Autofocus first window when no window is focused in a workspace

### ISSUE THREAD

**Issue by ItsProfessional** [hyprwm/Hyprland#2451]
I have firefox, wezterm, and discord autostart in my hyprland config, which are also assigned workspaces 1, 2 and 3 using window rules.

When hyprland starts, workspace 3 becomes the current workspace with discord is focused in it (I assume it's because discord is the window that starts at last)

All of that is fine, but when I switch to workspace 1 or 2 using keybinds, I assume that firefox and wezterm will be FOCUSED in those workspaces, but that is not the case.

So I have to manually focus it by clicking on windows (because I have `follow-mouse` set to `2` since I don't like hover selection). This means I can't type anything in the terminal without focusing it manually.

An option in hyprland to automatically focus the top-left-most window if there is no window focused in a workspace would be appreciated. I am coming from Sway, which has this feature built in, and I don't know why I should have to manually script such a basic feature like this

**Comment by memchr** [comment]
Hi, would you mind attaching your Hyprland configurations? Thanks.

**Comment by woojiq** [comment]
I'm not issue author but also encounted this. My config:
```conf
exec-once = hyprctl keyword windowrule "workspace 1 silent, Google Chrome"
exec-once = hyprctl keyword windowrule "workspace 2 silent, wezterm"
exec-once = google-chrome-stable
exec-once = wezterm
exec-once = /nix/store/bnx8z8asxh86ghxb7469k460zrzix2bl-cleanup-script
```
And `cleanup-script`:
```sh
sleep 4
hyprctl keyword windowrule "workspace unset, google-chrome-stable"
hyprctl keyword windowrule "workspace unset, wezterm"
```
Shortcuts for switching workspace:
```
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
...
```
My full config [home-manager module](https://github.com/woojiq/nixos-config/blob/main/modules/desktop/hyprland/home.nix)

I noticed that switching the workspace does not focus a windows, but I have `bind = $altMod, Tab, focuscurrentorlast`. And on launch i press `alt-tab` and it opens focused second workspace. A little workaround.

**Comment by memchr** [comment]
@woojiq Can you try this patch?

[0001-focus-first-window.patch.txt](https://github.com/hyprwm/Hyprland/files/12391958/0001-focus-first-window.patch.txt)

**Comment by woojiq** [comment]
It works fine. I will use the patched version until it is fixed upstream. If I find any strange behavior (unlikely), I'll ping you.

Off topic: How did you add the header (from, date, subject) for the patch? Have you used the `format-patch` git command?

**Comment by memchr** [comment]
> Off topic: How did you add the header (from, date, subject) for the patch? Have you used the format-patch git command

Yes, I did, so the commit can be recreated with metadata intact.

---

To the maintainers,

Should this be considered the appropriate default behaviour for Hyperland to automatically focus a window if no window is focused in a workspace, or should it only do this if a user explicitly configures it to do so?

**Comment by memchr** [comment]
@ItsProfessional Can I ask you a couple of questions?

What do you think should be the default behaviour when `input:follow_mouse != 1`?

When a workspace has multiple windows, which window should be focused, the first window or the window under the cursor?

> exec-once = [workspace 1 silent;noanim;noinitialfocus] firefox
> exec-once = [workspace 2 silent;noanim;noinitialfocus] wezterm
> exec-once = [workspace 3 silent;noanim;noinitialfocus] discord

In the above example, you have explicitly started firefox on workspace 1 with `noinitialfocus`, and there is no workspace switching since workspace 1 is what greets you when you start hyprland, **thus firefox would not be in focus on startup**, even with this patch. The sensible patch, IMO, at the moment is to change the workspace switching behaviour. 
So users might consider using `[workspace 1 silent;noanim]` instead if they want a window to be focused on startup. What do you think?

**NOTE**:
- All questions assume that
  - `input:follow_mouse != 1`.
  - the workspace has no previously focused window.

**Comment by memchr** [comment]
> that is, the window that is the top-left-most visually on the screen

Unfortunately contradicted, the first window on a workspace is not actually defined as the `top-left-most` window in Hyprland. It is the first non-hidden window in the `CCompositor::m_vWindows' that belongs to the workspace.   And it may not even be the first application launched in the commands you used above.

**Comment by memchr** [comment]
@ItsProfessional Sorry to bother you with this. Would you like to try this PR #3041? It shall (theoretically) focus on the top left hand window.

**Comment by aposteeltje-bwg** [comment]
Hi all.
I used i3-wm for years, and it has a unique feature:
auto_back_and_forth , which is applicable to workspaces.
So, what it does is:
Say, i'm on ws.2, running a browser.
I open a terminal, which opens on ws.1 and autom. switches to ws.1., bringing the terminal on top.
Now, when i invoke "Alt-Tab"., it switches back to the previously focused window, across workspaces, so it switches to ws.2 , bringing the browser on top.

When i close the terminal on ws.1 ., the exact same thing happens, and brings me back to ws.2 ., de browser focused.

I'm looking for the same functionallity for Hyprland, and the closest thing/setting i can think of is:

(since we can bind more commands to the same binding...)
bind = ALT, Tab, cyclenext                                    # cycle through applications on same workspace
bind = ALT, Tab, bringactivetotop                      # while cycling on same workspace, bring selected to top
bind = $mainMod, Tab, focuscurrentorlast     # bring back focus to previous focused window across workspaces

It somehow DOES work., allthough it's not really the same.
