### ISSUE TITLE
Unable to change the scroll_factor of external mouse

### ISSUE THREAD

**Issue by aadi58002** [hyprwm/Hyprland#2574]
```sh
mice:
	Mouse at 564493b56bc0:
		asus-keyboard-3
			default speed: 0.000000
	Mouse at 564493b5a590:
		elan1205:00-04f3:30e9-mouse
			default speed: 0.000000
	Mouse at 564493c06490:
		elan1205:00-04f3:30e9-touchpad
			default speed: 0.000000
	Mouse at 564493adaef0:
		liteon-dell-wireless-mouse-wm118-consumer-control-1
			default speed: 0.000000
	Mouse at 564493b25e80:
		liteon-dell-wireless-mouse-wm118-mouse
			default speed: 0.000000

```

```sh
device:liteon-dell-wireless-mouse-wm118-mouse {
    scroll_factor = 2.0
}
```
full config -> https://pastebin.com/2z2sHYgW

Hyprland Error in the top popup:-
Error setting value <2.0> for field <device:liteon-dell-wireless-mouse-wm118-mouse:scroll_factor>: No such field

I tried to change the sensitivity and natural scrolling options and they work as expected

**Comment by vaxerski** [comment]
oops, scroll factor exists only in touchpad: and doesnt per-device. Wiki bug

**Comment by aadi58002** [comment]
@vaxerski  is there a way to change the scroll factor for a external device ?

**Comment by vaxerski** [comment]
nope, wlroots limitation

**Comment by paolomainardi** [comment]
I don't know if this issue is still present, but Sway, which is based on wlroots, allows you to configure the scroll_factor of a mouse device. I am using it with an Mx Master with a scroll factor of 0.4.

Here is the doc: https://www.mankier.com/5/sway-input

**Comment by Nama** [comment]
Could this issue be opened again, please?

**Comment by gammons** [comment]
@vaxerski I think we should re-open this.  

I think we could add this pretty easily.  Sway does support a generic  [`scroll_factor`](https://manpages.debian.org/experimental/sway/sway-input.5.en.html) for external mice and I have a specific `scroll_factor` setting for my external mouse that is respected.

Looking at the [sway code](https://github.com/swaywm/sway/blob/master/sway/input/seatop_down.c#L137) it looks like it's just grabbing the config `scroll_factor` and just sending that along to `wlr_seat_pointer_notify_axis`.

The [Hypr code](https://github.com/hyprwm/Hyprland/blob/main/src/managers/input/InputManager.cpp#L667) is looking very specifically for the `input:touchpad:scroll_factor` value, and otherwise setting it to `1`.  

I'm wondering if we could have a more generic `input:scroll_factor` value that we could use instead of 1 that we could use if we detect the source is not a touchpad.

I'm happy to put a PR together if that makes sense, although I'm not a CPP developer.

**Comment by paolomainardi** [comment]
Another issue i noticed is that Firefox does not respect that value, while chromium-based browser do.

**Comment by gammons** [comment]
I did change this line https://github.com/hyprwm/Hyprland/blob/main/src/managers/input/InputManager.cpp#L671 from a `1.f` to a `1.5f` (which replicates my sway setup) and it's working correctly.

@vaxerski should I put in a PR?  would it make sense to have this as a config variable `input:scroll_factor`?  (probably assumes that people only have one external mouse, but maybe that's an ok assumption)

**Comment by vaxerski** [comment]
u can

**Comment by gammons** [comment]
PR was just merged folks :tada:
