### ISSUE TITLE
Windows not visible.

### ISSUE THREAD

**Issue by niksingh710** [hyprwm/Hyprland#2599]
On rare occasion after coming from suspend the windows on a specific workspace are not visible they will get focused and all but won't be visible.

**Comment by MightyPlaza** [comment]
what's the hyprctl clients info?

**Comment by niksingh710** [comment]
> what's the hyprctl clients info?

That's list the windows with the correct workspace mentioned.

**Comment by MightyPlaza** [comment]
yes but what does it say about the "invisible" windows?
at, hidden, ... ?

**Comment by niksingh710** [comment]
> yes but what does it say about the "invisible" windows?
> at, hidden, ... ?

Yes it does

**Comment by Ordoviz** [comment]
I just got an invisible window on workspace 2:
```console
$ hyprctl clients
Window 55a254ebcfe0 -> newsboat ~:
	mapped: 1
	hidden: 1
	at: 0,30
	size: 2560,1410
	workspace: 2 (2)
	floating: 0
	monitor: 0
	class: foot
	title: ~
	initialClass: foot
	initialTitle: foot
	pid: 1512
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0

$ hyprctl workspaces
workspace ID 2 (2) on monitor eDP-1:
	windows: 1
	hasfullscreen: 0
	lastwindow: 0x0
	lastwindowtitle:
```

I only noticed this because waybar shows workspace 2 as non-empty, everything else works fine. The only thing unusual is that the invisible window has `hidden: 1`. This probably happened because newsboat became hidden when it got swallowed by mpv, but it wasn't unhid when mpv exited.
 
I think I last saw an invisible window a few months ago, so it happens very rarely. I didn't suspend.

**Comment by vaxerski** [comment]
@Ordoviz that's unrelated, but if you find a way to repro, make a bug report :)

**Comment by MightyPlaza** [comment]
should original issue be closed?
there isn't really much information to use

**Comment by vaxerski** [comment]
prolly
