### ISSUE TITLE
`cursor_inactive_timeout` un-hiding issues

### ISSUE THREAD

**Issue by y0nei** [hyprwm/Hyprland#2658]
I use the `cursor_inactive_timeout` option with a timeout of `5`
My issue is that the cursor sometimes un-hides after some delay for some reason (instead of the un-hiding being instant in most cases), i can even see browser ui elements highlighted indicating that the cursor position indeed does change but it has a wierd delay on being rendered back again from being hidden.
The cursor appears again once i hover on another wayland window like eg. `waybar`, or sometimes after a short while by itself

Not sure if this is even relevant but here are all the GTK/Cursor related settings i use:
```yaml
### GTK Related
env = GTK_THEME,Nordic
env = XCURSOR_THEME,Breeze_Snow
exec-once = hyprctl setcursor Breeze_Snow 24
exec-once = gsettings set org.gnome.desktop.interface cursor-theme Breeze_Snow
exec-once = gsettings set org.gnome.desktop.interface icon-theme Vimix-dark

env = XCURSOR_SIZE,24
env = WLR_NO_HARDWARE_CURSORS,1
```

**Comment by fdev31** [comment]
Same here, since a very long while, and even when using hyprcursor format.

- set something like `cursor_inactive_timeout = 2`
- open a window where highlight is visible (eg: web browser with links/buttons)
- do not move the mouse, it will hide
- start moving the mouse: the cursor is not visible while app responds to the cursor movements

The cursor will only get visibility when the focus moves out of the currently focused client window

Note: I'm also using `WLR_NO_HARDWARE_CURSORS=1` but I don't think it's related.

**Comment by fdev31** [comment]
Additional note: without the cursor_inactive_timeout set the cursor may still hide and can be challenging to recover (even switching workspaces / client focus / ...)

**Comment by izmyname** [comment]
Is this still the case?

**Comment by y0nei** [comment]
stopped using hyprland
