### ISSUE TITLE
always open apps in specific workspace

### ISSUE THREAD

**Issue by mairm1340** [hyprwm/Hyprland#2712]
HI
I have 10 work space. 
I want to open say firefox in workspace 2 always.
can someone help me or guide me. I did read Wiki but could not figure that out.

I have 5-6 apps which I work on every day and I want them to open always in specific workspace. 

I do use Xmonad and I was able to achieve and now started using Hyperland.

**Comment by MightyPlaza** [comment]
https://wiki.hyprland.org/Configuring/Window-Rules/

**Comment by mairm1340** [comment]
thank you so much

windowrulev2 = workspace 2, class:^(firefox)$
windowrulev2 = workspace 2, class:^(microsoft-edge)$
windowrulev2 = workspace 2, class:^(Microsoft-edge)$
windowrulev2 = workspace 2, class:^(Google-chrome)$
windowrulev2 = workspace 3, class:^(Prospect Mail)$
windowrulev2 = workspace 4, class:^(teams-for-linux)$
windowrulev2 = workspace 8, class:^(thunar)$
windowrulev2 = workspace 1, class:^(alacritty)$

It works now!!

**Comment by dozothebozo** [comment]
exec-once = discord-canary
windowrulev2 = workspace 5 silent, class:^(discord)$

this worked for me, it opens discord-canary on workspace 5 without jumping when it starts

**Comment by icyleaf** [comment]
@dozothebozo you can merge this:

```
exec-once = [workspace 5 silent] discord
```

**Comment by Yolsh** [comment]
is there a way to do this so that multiple window rules are applied at exec-once for instance i would like my terminal to open in special workspace and be in full screen. I have tried:
`exec-once = [workspace special silent] [fullscreen] $terminal`
but this just doesn't open it. but when i remove the `[fullscreen]` it works again.
any help would be much appreciated

**Comment by Yolsh** [comment]
thanks for the quick response, worked perfectly
