### ISSUE TITLE
Transparent windows sometimes show wrong background with blur optimizations enabled

### ISSUE THREAD

**Issue by Roger-Roger-debug** [hyprwm/Hyprland#2941]
### Hyprland Version

Hyprland, built from branch main at commit e4e8ae8f885104bb948afa24f1cd9fc3bdb450e9 dirty (dwindle: disallow togglesplit on fullscreen).

### Bug or Regression?

Bug

### Description

With the blur optimization enabled I sometimes see hypr-chan on my transparent windows (as opposed to my background). 

Either disabling the optimizations or setting a new background makes the correct background show up.

I'm not sure if this even is a bug or just how the optimization works.

### How to reproduce

I do not know how to reliably reproduce this issue.

**Comment by vaxerski** [comment]
> I do not know how to reliably reproduce this issue.

Neither do I, let me know if you find a way. Never seen this.

**Comment by Roger-Roger-debug** [comment]
I can more or less reproduce the issue reliably now. Whenever I watch a video in firefox for some time and then exit fullscreen all windows will show the default hyprland background, empty workspaces show the proper background. The next time my script changes the wallpaper the issue fixes itself.

**Comment by Roger-Roger-debug** [comment]
I don't think so. Once the bug is triggered it happens for all windows (I'm on my laptop, don't know how it works with multiple monitors). I tried to take a screenshot but that too fixes the wrong background being shown...

**Comment by vaxerski** [comment]
oh wait

**Comment by vaxerski** [comment]
I don't seem to be able to repro. You're somehow triggering a blur fb repaint while half the code doesn't know about it.

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/12323927/patch.txt)

try this patch

**Comment by Roger-Roger-debug** [comment]
That seems to have worked, thank you for the quick fix :)

**Comment by MahouShoujoMivutilde** [comment]
@vaxerski Can we get this patch merged?

I've too been using it for a few days, and not only does it fix hypr-chan background sometimes showing up instead of mine, it also gets rid of another issue\* with blurred background that I've been trying (unsuccessfully) to find a reliable way to reproduce.

(\*) - sometimes windows with blurred background will get an imprint of a part of some window on another workspace (this will typically be firefox).

<details>
  <summary>Demo</summary>

https://github.com/hyprwm/Hyprland/assets/14999778/dd4248d8-692e-4df0-9c13-f4de9930bb4f

</details>

I could generally reset the background by either opening [tofi](https://github.com/philj56/tofi) or toggling floating for the window.

Now it doesn't happen anymore (It usually did at least few times a day).
