### ISSUE TITLE
Blender is unusable.

### ISSUE THREAD

**Issue by aspizu** [hyprwm/Hyprland#3024]
### Hyprland Version

Hyprland, built from branch  at commit 9654749244117f7f150c6f2a2ce4dede6e8cbb25 dirty (). Tag: v0.28.0  flags: (if any)

### Bug or Regression?

Bug

### Description

Blender window cannot be resized, moved, interacted with.
Clicking in the center of the UI seems to work but as you go farther from the center, it becomes unresponsive.

### How to reproduce

In on a HiDPI monitor.

### Crash reports, logs, images, videos

`hyprland-0.28.0-1` on Arch Linux

`Blender 3.6.0`

**Comment by imxyy1soope1** [comment]
use this:
hyprland.conf
```
---SNIP---
windowrule = nomaximizerequest, ^(blender)$
---SNIP---
```

**Comment by aspizu** [comment]
That fixes the resizing issue but the UI is still unresponsive. Context-menus don't get drawn until i move the mouse pointer. It seems like the UI doesn't redraw until I move the mouse around.

**Comment by Brotbrett** [comment]
Do you perhaps have multiple graphics cards in your system?

If so, then it could be due to the `PrefersNonDefaultGPU` field in Blender's .desktop file.
Which per default is located at `/usr/share/applications/blender.desktop`.

After changing the field to false or removing it completely, the issue should be resolved temporarily.

**Comment by aspizu** [comment]
That seems to work, thanks.

**Comment by mfdorst** [comment]
You should close this issue if you found a solution.
