### ISSUE TITLE
Blur on Waybar

### ISSUE THREAD

**Issue by GabrielMrqs** [hyprwm/Hyprland#3126]
### Hyprland Version

0.28.0-1

### Bug or Regression?

Bug

### Description

I added this line to my hyprland.conf

>blurls = waybar

It starts blurred, but after 1s, blur turns off.

### How to reproduce

>blurls = waybar 
on hyprland.conf

### Crash reports, logs, images, videos

![image](https://github.com/hyprwm/Hyprland/assets/80988043/be28536a-7c57-4e6f-8387-f8e46e2a84be)

just started:
![image](https://github.com/hyprwm/Hyprland/assets/80988043/d2508101-7f18-46c5-b6fd-b86c8a446cc4)

after 1s:
![image](https://github.com/hyprwm/Hyprland/assets/80988043/39eccd15-7be5-43d8-a7a3-1213ac465445)

**Comment by tchofy** [comment]
Try ``layerrule = blur,waybar`` instead, I think ``blurls`` was deprecated considering ``layerrule`` is more recent and has more options.

**Comment by GabrielMrqs** [comment]
> Try `layerrule = blur,waybar` instead, I think `blurls` was deprecated considering `layerrule` is more recent and has more options.

I did this too, but still turning off :cry:

**Comment by Hubro** [comment]
`layerrule = blur,waybar` works perfectly for me, with hyprland 0.28.0 and waybar 0.9.22

**Comment by RedBlizard** [comment]
I'm currently running hyprland-git and waybar-hyprland-git  without issues,but if i want to run the version hyprland 0.29.1-1  and still use waybar-hyprland-git  with the correct blur rule enabled layerrule = blur,waybar and i switch my wallpaper with swww then for some reason a part of the old wallpaper stays behind waybar, if i turn of blur for waybar the problem is gone if i switch out waybar-hyprland-git for waybar-hyprland 0.9.22-1 it all works fine only when i reboot it take almost 2 to 3 minutes for waybar to load. so what could be the problem here ?

**Comment by Erothas** [comment]
I have been having this issue since I started using hyprland months ago. It was annoying, but I was too lazy to make an issue about it. Thanks for shedding some light on it.

**Comment by RedBlizard** [comment]
the problem is caused by xdg-desktop-portal, i did mask it even when that service was not running, xdg-desktop-portal-hyprland is not masked.

sudo systemctl mask xdg-desktop-portal.service
Did the trick so the porblem is caused by xdg-desktop-portal !

**Comment by RedBlizard** [comment]
Did found out that also the slow loading of waybar, is caused by xdg-desktop-portal-hyprland, removing the portal solves the issue.

**Comment by GabrielMrqs** [comment]
Hey, I just found that the property `opacity: 0.5` in my Waybar config was the issue. I removed it, and it's working perfectly now.
Life is good.
![image](https://github.com/hyprwm/Hyprland/assets/80988043/93bdf06f-9a56-4796-9b56-c2fbc0bf10e7)

**Comment by pinkoboio** [comment]
I know this issue is closed but I'm not sure where else I could get help with it. I have the exact same issue as op (The bar blur persists for a moment before disappearing), however removing the `opacity` option in the style.css file just makes the bar opaque. I have set my background color using `rgba( r, g, b, a )`, and still the bar remains opaque. I have tried `layerrule = blur,waybar` and `blurls = waybar` both to no avail. Again I know this issue is closed but I don't see a better place to get help with this.

**Comment by arukon-prime** [comment]
I had two problems, including one with blurring. I'm using NixOS. I'll leave a note here in case it helps someone.
version waybar: `0.10.3` ; version hyprland: `0.41.2`

1) When launching "waybar," I encountered an error: "`Unable to receive desktop appearance: GDBus.Error.freedesktop.DBus.Error.UnknownMethod:...`"
The cause was the absence of xdg.portal (gtk) on my system, which I resolved by adding xdg.portal to the Nix configuration:
```nix
{ pkgs, ... }:
{
	xdg.portal = {
		enable = true;
		extraPortals = [ pkgs.xdg-desktop-portal-gtk ];
		xdgOpenUsePortal = true;
	};
}
```
2) Just like you, the blurring would disable itself after a second. I don't know the cause. I fixed it by removing the opacity setting in waybar.css and replacing background-color with transparent, it worked for me. The result is:
```css
window#waybar {
	background-color: transparent;
	transition-property: background-color;
	transition-duration: .5s;
	border-radius: 5px;
}
```

**Comment by ashish-kus** [comment]
This might solve your issue.
```
window#waybar {
      background: rgba(17, 17, 27, 0.7); /* Semi-transparent */
 }
```

**Comment by Nosferath** [comment]
> This might solve your issue.
> 
> ```
> window#waybar {
>       background: rgba(17, 17, 27, 0.7); /* Semi-transparent */
>  }
> ```

This only makes it semi-transparent. The idea is to make it have blur.

I have tried the above solutions to no avail.

EDIT: I got it to work somehow with the semi-transparent background and `layerrule = ignorezero, waybar` in `hyprland.conf`. I don't know why it was not working before.

**Comment by loganswartz** [comment]
I ran into this issue, and none of the suggestions here or elsewhere worked for me. In case anyone else stumbles upon this, here's what worked for me.

Some quick background: I'm using matugen, so I have an autogenerated `colors.css` that I import into my waybar config that contains all my colors. With my matugen setup, `colors.css` is shared with several other programs, so I didn't want to hardcode the opacity into `colors.css` itself, so `colors.css` is just filled with plain RGB (not RGBA) hex color values:

```css
/** .config/waybar/colors.css */

@define-color background #121318;

/** ...etc */
```

I had read that the `opacity` CSS property worked in waybar, so I thought I could just specify a plain RGB hex color (ex: `#121318`) and an `opacity` (ex: `0.25`) to get the same effect as passing an RGBA hex color (ex: `#12131844`):

```css
/** .config/waybar/style.css */

@import "colors.css";

window {
  background-color: @background;
  opacity: 0.25;
}
```

This partially worked; the opacity and color works, but you get absolutely no blur. **_It seems that blur misbehaves when you try to obtain the transparency from `opacity`, instead of directly from the color value. So, the solution is to only supply the transparency through the color._** If you're in a situation like I am, you can mix transparency into an existing color via the `alpha` helper, which GTK luckily supports:


```css
/** .config/waybar/style.css */

@import "colors.css";

window {
  background-color: alpha(@background, 0.25);
}
```

This, combined with `layerrule blur,waybar` got everything working properly for me.
