### ISSUE TITLE
Mouse teleporting

### ISSUE THREAD

**Issue by Izaird** [hyprwm/Hyprland#3224]
### Hyprland Version

v0.29.1-33-g66482747

### Bug or Regression?

Bug

### Description

Mouse is teleporting on blender when trying to pull a menu

### How to reproduce

Open blender (flatpak) and drag a menu to merge it

**Comment by Izaird** [comment]
https://github.com/hyprwm/Hyprland/assets/31055847/8133be2d-1e8e-4c22-9b50-e27ac63e812d

**Comment by vaxerski** [comment]
suspicious version, can you try updating to the latest git?

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/12565612/patch.txt)
would you please be so kind to attempt at verifying whether this software patch fixes the aforementioned issue?

**Comment by Astonishskagen** [comment]
Hello, 

I just wanted to add my experience as well. Me too since yesterday I am facing a similar problem on Blender. When I click on anything on Shader Editor window or properties panel or when I try to add or remove workspace, my mouse jumps to the top left corner. I tried it both with:

- Blender 3.6 LTS downloaded from the Blender web site
- Flatpak Blender 3.6
- Blender 4.0 alpha

And the problem happens on all of them. I have this problem on both of my laptops running endevouros and hyprland:

- Lenovo Legion 7 with AMD Ryzen 5800H CPU and Nvidia RTX Gpu
- Lenovo Yoga Slim 7 Pro with AMD Ryzen 6800HS Cpu and integrated AMD Gpu

I have downloaded the path.txt file but I am still a Linux noob on these stuff ( 8 months of using Linux ) so I wouldn't know how to apply it to report back. Should I run those on terminal? Should I run it like a script by making it executable witch sudo chmod +x ?

**Comment by vaxerski** [comment]
google is your friend

**Comment by cufffs** [comment]
I had a similar issue (GuildWars2 running through steam/proton) would move the mouse randomly to top left screen after latest updates.

I applied this patch and it has helped a little, but now the mouse moves to center of the screen (like in the video by OP) instead of top left. But at least when it does it I don't constantly open up the menu over and over

**Comment by vaxerski** [comment]
that... should not be the behavior of the patch.

**Comment by Ghosthree3** [comment]
I was experiencing this same issue with another application, Looking Glass (a sort of remote viewer for Windows VMs).
On the latest release (0.29.1) the cursor would teleport to 0x0 of the monitor whenever it exited the viewing area. On master it would either fail to escape at all or be teleported back to center.
But I'm happy to report that after building with the patch linked above the mouse seems to be behaving as expected and the issue is now resolved (for me).

**Comment by vaxerski** [comment]
pushed the patch, I consider this closed
