### ISSUE TITLE
Mouse teleporting while adjusting values on blender

### ISSUE THREAD

**Issue by Izaird** [hyprwm/Hyprland#3270]
### Hyprland Version

v0.29.1-56-ged51fe7b

### Bug or Regression?

Bug

### Description

Mouse teleports to the center of the screen when dragging value to adjust it 

### How to reproduce

Hold and drag value 

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/31055847/1d050641-081f-438a-ad6e-2db05c38fd31

_No response_

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/12584755/patch.txt)

try zis

**Comment by memchr** [comment]
Does not work, cursor still warps to centre.

**Comment by vaxerski** [comment]
hm. Will have to install that hunk of garbage and test then. I hope this happens on the normal packaged release?

**Comment by memchr** [comment]
> normal packaged release

You mean stable blender release? Yes.

**Comment by antonamurskiy** [comment]
I have the same issue (on the stable blender release)

**Comment by gabor-motko** [comment]
I had the same issue when I tried to update to 0.29.0, and again with 0.29.1. The cursor would warp to the top-left corner of the window every time I try to click into or adjust a numeric value. `hyprland-git` presents a similar issue, except the cursor warps to the center of the window rectangle. 0.28.0 compiled from source, however, didn't have this issue.

Of particular note is the fact that this only happens with certain UI elements.
- The numeric input field actually hides the cursor on a mouse-down event because it also responds to horizontal mouse movement, and unhides it on mouse-up.
- Resizing UI areas in Blender presents the same issue, but only on mouse-up.
- Splitting an area in half, or joining two adjacent areas, by dragging on the corners where they meet presents the same issue.
- Dragging or resizing nodes, or connecting wires in the node editor.
- Using a sculpting, painting, or drawing tool.

This does NOT happen in many other cases:
- Non-numeric inputs
- Using selection (rect, circle, lasso) tools
- Dragging curve points in the graph editor
- Dragging keyframes in the dope sheet

This is 0.29.1 from the Arch package.
https://github.com/hyprwm/Hyprland/assets/37093630/dbabb812-5658-4527-b080-0ed0b53beb79

**Comment by vaxerski** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/43317083/322a09c8-6a01-466b-a57c-a9a81eb9a3ef)

god forgive me for I have sinned

**Comment by vaxerski** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/43317083/021c6555-4a98-4932-9189-e48d7f5fb941)

this doesn't help.

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/12622624/patch.txt)

try this patch

**Comment by gabor-motko** [comment]
> try this patch

Much better. It fixed most of the occurences, except the numeric inputs. Both dragging and clicking into them snaps the mouse to the window's center.

**Comment by vaxerski** [comment]
I pushed the patch. For the numeric inputs, can I get a video?

**Comment by gabor-motko** [comment]
I can't record it right now, but it's almost the exact same as the video in my previous comment. The first thing I show there is the numeric inputs - dragging first, clicking second. The only difference now is that the cursor moves to the center instead of the corner.

**Comment by memchr** [comment]
> ![image](https://user-images.githubusercontent.com/43317083/268363109-021c6555-4a98-4932-9189-e48d7f5fb941.png)
> 
> this doesn't help.

Blender in the Arch repo depends on the open shading language, which has a hard dependency on llvm15, causing a segfault.

testing repo works: https://archive.archlinux.org/packages/b/blender/blender-17%3A3.6.2-6-x86_64.pkg.tar.zst

**Comment by vaxerski** [comment]
please check #4889

**Comment by rurigk** [comment]
Tested and its working correctly for me 
Im not sure if this is relevant for this issue but i dont use any scaling

**Comment by Breadp4ck** [comment]
![fix](https://github.com/hyprwm/Hyprland/assets/36762759/31ed1196-8120-42bd-ad40-68e9f857454a)

You may ignore the issue if you deselect the Continues Grab setting.
