### ISSUE TITLE
togglespecialworkspace doesn't toggle special workspace

### ISSUE THREAD

**Issue by Jaques22** [hyprwm/Hyprland#3311]
### Hyprland Version

Hyprland, built from branch  at commit 2536630049f3847c0c44340f4706f3664c8b52fb  (). Tag: ?  flags: (if any) debug

Same behaviour present at commit 84f8f4d77ddf4b6c772459584234e1f8f9d5f2ce

### Bug or Regression?

Regression

### Description

The togglespecialworkspace dispatcher doesn't switch the the special workspace. It just slightly dims the screens.

### How to reproduce

Latest hyprland-git build. 
I have the following in my hyprland.conf:
`exec-once = hyprctl dispatch exec [ workspace special:fm silent ] kitty ranger `.
`bind = $mainMod, W, togglespecialworkspace, fm`
Now when press my bind to open the special workspace, the screen slightly dims but the workspace doesn't actually open. 
I tried running the command in term and it outputs "okay" but the special workspace doesn't actually open, just dims screen. 

However when i run: `hyprctl dispatch exec [ workspace special:fm ] kitty ranger ` in a term (without the silent flag), the special workspace pops into view with multiple ranger windows open. 
The togglespecialworkspace bind still doesn't work

### Crash reports, logs, images, videos

In the video below you can see the dimming when I'm activating the togglespecialworkspace bind. 
https://github.com/hyprwm/Hyprland/assets/38633150/514ea550-36a7-4be0-9994-508895ffd926

**Comment by Yaakoss** [comment]
It seems the same regression/error is happening again.

togglespecialworkspace only dims the screen slightly and does not toggle the specialworkspace.

**Comment by didacd** [comment]
I think this issue has reappeared in `v0.51.1`. I was able to successfully reproduce it in my machine.


---
Specs:
```
Hyprland 0.51.1 built from branch  at commit 71a1216abcc7031776630a6d88f105605c4dc1c9  ([gha] Nix: update inputs).
Date: Mon Sep 22 20:54:03 2025
Tag: v0.51.1, commits: 6436
built against:
 aquamarine 0.9.5
 hyprlang 0.6.3
 hyprutils 0.10.0
 hyprcursor 0.1.13
 hyprgraphics 0.2.0

no flags were set
```
---

Switching to a special workspace, and then trying to go back to the previous one doesn't work. As it calls again for the special workspace instead of returning to let's say workspace `1`.

Executing `hyprctl monitors -j | jq '.[].specialWorkspace'` while in the special workspace returns:

```json
{
  "id": -95,
  "name": "special:magic"
}
{
  "id": 0,
  "name": ""
}
```

It is worth mentioning that while focusing a special workspace, normal workspaces can be accessed, but not used due to `magic` (in my case) is perpetually focused.

The special workspace I configured looks like this:

```
workspace = name:magic
bindd = SUPER, s, Switch to special workspace, togglespecialworkspace, magic
bindd = SUPER SHIFT, s, Move to special workspace, movetoworkspace, special:magic
```

**Comment by sunknown** [comment]
Have the same problem on 0.52.1 version. Basically same setup as a previous message.
