### ISSUE TITLE
Remove young girl image from default (non)background

### ISSUE THREAD

**Issue by acidkewpie** [hyprwm/Hyprland#3412]
### Description

It's 2023, the image is not appropriate.

Having such an image randomly appear with each random video driver glitch and such is wrong. I'm fully aware that this can be disabled, but this is not a significant justification. Having to explicitly opt out of seeing it is not a justifiable reason to leave it within the Hyprland codebase.

It is clearly sexually loaded. If not, there would be an alternative with a visually male alternative, or potentially a person with no identifiable gender. Neither of these are the case, only a single, unrealistic image of a young girl. 

Outside of social sensitivities It is also just irrelevant. It is a very professional, high quality graphic, but it is not the Hyprland logo, it's not meaningful and has nothing whatsoever to do with a window manager. It should not be there. If someone likes it, great, they are free to go set it as their own personal wallpaper. This is not Hyprland's place.

**Comment by vaxerski** [comment]
it's the mascot. It's like complaining about seeing tux.

I hope this is satire.

**Comment by acidkewpie** [comment]
Tux is not sexual, nor gendered. That is not in any way an appropriate comparison. Cmon, there's just no need for it.

**Comment by vaxerski** [comment]
that's just your opinion.

Sexual? Neither is hypr-chan. Maybe you should stop seeing anything resembling a human as "sexualized"? It would be healthy.

**Comment by NotAShelf** [comment]
> It's 2023, the image is not appropriate.

what is not appropriate, the female gender?

**Comment by burein-ita** [comment]
hypr-kun when

**Comment by meedstrom** [comment]
Here's a way to know it is sexualized: if you feel that you probably wouldn't choose a human mascot in the first place if it had to be any other type of human, that definitely means it's sexualized.  We don't know you, @vaxerski, so only you can answer that.  it just looks very likely from the outside, based on the majority of people who save/collect/display this kind of imagery.  And because of that, the mascot becomes a clear political signal, whether you mean it or not.

I'm sure there's a part of you that knows exactly what OP means, and knows perfectly well that Tux isn't a fair comparison.
