### ISSUE TITLE
Add keybind event to socket2.

### ISSUE THREAD

**Issue by aspizu** [hyprwm/Hyprland#3439]
### Description

Add a way for keybinds to trigger events in socket2.
Currently, `hyprland-py` achieves this by implementing our own socket.

Configuration:
```
bind=SUPER,E,custom_event,my_event
```

**Comment by MightyPlaza** [comment]
can't this be done with the plugin system?

**Comment by vaxerski** [comment]
can be but this is a fair core feat

**Comment by anderso** [comment]
I second this. I imagine a new dispatcher named `event`, which enables me to do this for example:

```
bind=SUPER,M,event,focusmain
bind=SUPER,1,event,focusother1
bind=SUPER,2,event,focusother2
```

so that pressing SUPER+M would for example trigger an event like this:

`dispatchevent>>focusmain`

And I could implement my custom focus logic in my own process. The alternative I guess is using `exec` and some custom IPC, but this would be much simpler and avoid the overhead of spawning a processes for each key press. Maybe you also should be able to set the event name? Maybe enable you to leave out the data to send, and then instead send some representation of the bind that triggered the event and you can parse it in your own process?

**Comment by vaxerski** [comment]
I can do it
