### ISSUE TITLE
VFR causes white flashes / brightness flickers on some hardware

### ISSUE THREAD

**Issue by ThatOneCalculator** [hyprwm/Hyprland#351]
About every 20-60 seconds, I get random white flashes on my monitor. This never happened before c0c75db62188667a4f42aef1ae6bfd8034093af7 .

GPU is a RX 6700XT.

**Comment by vaxerski** [comment]
hm, weird. Maybe I should add an option to disable it. Maybe your monitor doesn't like it..?

**Comment by vaxerski** [comment]
also by flashes you mean just one blink or multiple?

**Comment by vaxerski** [comment]
added `misc:no_vfr` in 29e2bb27f6073695aa4f9767f87cd653db5ce811, you can use that

**Comment by ThatOneCalculator** [comment]
Flashes are one at a time. I'll try that in the morning.

**Comment by ThatOneCalculator** [comment]
Also can I ask exactly *what* VFR is?

**Comment by vaxerski** [comment]
variable frame rate.

**Comment by ThatOneCalculator** [comment]
Gotcha, it's probably my monitor not liking that. I'll lyk the results in the morning

**Comment by vaxerski** [comment]
maybe vfr should be off by default.

**Comment by ThatOneCalculator** [comment]
> maybe vfr should be off by default.

Agreed.

**Comment by vaxerski** [comment]
it now is

**Comment by ThatOneCalculator** [comment]
Cool. This issue should still be open until the issue is fixed, unless it's not planned.

**Comment by ThatOneCalculator** [comment]
Hm... maybe something that could be addressed far down the line?

**Comment by KyleUltimate** [comment]
I can confirm that this also happens for me, upon enabling vfr, white stuff starts to happen

**Comment by pechano** [comment]
I may have something interesting to try out, for people affected by this issue. On my setup (AOC AG27QXP + Radeon 5700XT) I have noticed that adaptive sync can work just fine under Wayland GNOME (using Mutter), but the two wlroots compositors I have tried had issues out of the box. These two being Sway and Hyprland. When I used Sway I figured out (by accident) that if I switched the refresh rates around a few times, I would get rid of the white flashing normally caused by adaptive sync/vfr options. I tried doing it with the Hyprland equivalent commands and it worked. So I just wanted to share it, in case others have the same issue. I have not seen any mention of a solution anywhere.
My display is 165hz adaptive sync, and to get it working without any white flashing I ran these three commands:

```plain
hyprctl keyword monitor DP-1,2560x1440@60,0x0,1
hyprctl keyword monitor DP-1,2560x1440@120,0x0,1
hyprctl keyword monitor DP-1,2560x1440@165,0x0,1
```
These are what worked for me, so I just threw them in a script that is executed once per startup. Because there is no sleep in between, it takes less than a second. The monitor blacks out in the switch from 60hz SDDM anyways, so I don't even notice it.

It did take a bit of experimenting, so your results may vary. But please let me know if this method is viable on your setup.

**Comment by vaxerski** [comment]
follow the issue here: https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3514

**Comment by pechano** [comment]
The brightness flickering that you describe in the wlroots question is exactly what I experience before setting the mode a few times. And only on the VFR monitor. The other one is fine.

**Comment by vaxerski** [comment]
If you can comment there too with all your findings it'd be great. Let me try on my monitors. Funnily enough, both are VFR but I don't notice the flickers on one of them. Maybe I am just blind.

**Comment by vaxerski** [comment]
oh shit you're right, it does seem to go away if I reload the mode. Wtf?

**Comment by vaxerski** [comment]
think I fixed it in 1b349f79acd29bf7589472147ec3853b6cad71b7

**Comment by vaxerski** [comment]
anyone can confirm?

**Comment by vars1ty** [comment]
Can check in ~1h if nobody else does it before me.

**Comment by vars1ty** [comment]
Just checked and seems to have no abrupt brightness changes anymore

**Comment by vaxerski** [comment]
waiting for OP @ThatOneCalculator

**Comment by ThatOneCalculator** [comment]
I just woke up. Give me <30 mins 🙏

**Comment by ThatOneCalculator** [comment]
After extensive testing I believe this issue is now resolved.

**Comment by inxiti** [comment]
Happening to me quite extensively if I don't have "no_vfr = true" set. Pretty frustrating.

**Comment by pechano** [comment]
Yeah a recent update even broke my homemade solution. I can't even "step" into VFR anymore.
I have not tested with sway.

**Comment by vaxerski** [comment]
do a `git bisect` then, but the only culprit I can see is the updated wlroots dep.
