### ISSUE TITLE
Graphical Corruption when toggling fullscreen mode with vrr=2

### ISSUE THREAD

**Issue by Gliczy** [hyprwm/Hyprland#3580]
### Hyprland Version

Hyprland, built from branch main at commit 424c9a7e704590db5c823557e5e388e366f7b1cd dirty (render: stop locking SWC on tearing). Tag: v0.30.0-86-g424c9a7e

### Bug or Regression?

Regression

### Description

Hyprland v0.29.0 has introduced a graphical corruption issue that was not present in v0.28.0 and earlier version.

When VRR is set to `vrr=2`, toggling fullscreen mode results in graphical corruption during both entry and exit of the fullscreen mode. This does not occur when VRR is set to `vrr=0` or `vrr=1`.

I use two monitors, with only one of them supporting VRR, yet I can replicate this issue on both monitors as long as VRR is set to `vrr=2`.

Notably, prior to v0.29.0, setting `vrr=2` globally did not display any graphical corruption on neither monitor.

### How to reproduce

Set `vrr=2` and then either spam toggle fullscreen or move the mouse while toggling fullscreen.

Another way to trigger this is to move my mouse from one monitor to the other and back again, graphical corruption will occur even without spamming or moving the mouse during fullscreen transition, but only for the first toggle cycle.

### Crash reports, logs, images, videos

[hyprland.log](https://github.com/hyprwm/Hyprland/files/12909836/hyprland.log)

**Comment by vaxerski** [comment]
`git bisect` please

**Comment by Gliczy** [comment]
I couldn't pinpoint a faulty commit using `git bisect`.
Since I was going nowhere with that, I decided to test the binary releases from GitHub.

I found that the `v0.28.0` release binary is functioning properly with no graphical corruption. However, when I manually compile `v0.28.0`, graphical corruption occurs.

Furthermore, I tested the `v0.27.0` release binary and encountered no graphical corruption.
This issue also persists in newer binary releases, including `v0.29.0`, `v0.29.1`, and `v0.30.0`.

**Comment by vaxerski** [comment]
if anything, this is an issue with wlroots or amdgpu, but I think it's just a thing that happens when you toggle vrr

**Comment by patrickr-de** [comment]
I've the same issue, with various glitches happening on plasma and mutter-vrr, too. So I guess it is indeed something that needs to be fixed by amd or wlroots.
Just to add however, since I've played around with my config all day:

I have two monitors - 75Hz and 144Hz, both with freesync.

75Hz, 144Hz, both vrr = 2: This config will introduce a 2-3s long black screen when toggling fullscreen.
60Hz, 120Hz, both vrr = 2: This config gets rid of the black screen, making the transition to fullscreen instant, however it introduces the graphical glitches
72Hz, 144Hz, both vrr = 2: This again results in black screens.

No differences with various combinations of vrr on both monitors. For comparison, I've also tested the behavior on plasma today, and 75/144 results in constant back and forth black screens (pretty much unusable), while 60/120 works flawlessly with no glitches happening.
