### ISSUE TITLE
I cannot engage with the Hyprland community on Discord

### ISSUE THREAD

**Issue by MrPixel1** [hyprwm/Hyprland#3643]
### Hyprland Version

None yet (?)

### Bug or Regression?

Bug

### Description

I'd like to engage with the Hyprland community to ask questions and exchange ideas etc, but that seems to be impossible because the Hyprland website only links to Discord; a restrictive, malicious and privacy invasive web service and proprietary product.

While I have tolerated it in exceptional situations before, it seems that now, for joining the Hyprland "server", I have to enter my phone number and verify it. Unfortunately, this is where my tolerance of the platform ends.

I could go on with the irony of promoting a proprietary application that doesn't even properly work on your very own WM, or how inappropriate it is to lure unsuspecting users and to make them give up their freedom, but I'm certain those who read this far got the point.
(If not, I *highly* recommend [this Article on gnu.org](https://www.gnu.org/proprietary/proprietary.html) that explains the major issues with proprietary software.)

---

### Suggestion

Because a community cannot be moved from one platform to another very easily, suggest enabling more than one platform, and connect them.

Specifically speaking, this could be a [Matrix space](https://matrix.org/docs/chat_basics/public-rooms/#spaces) where channels are [bridged with Discord channels](https://matrix.org/ecosystem/bridges/discord). A similar solution could be possible [with IRC](https://github.com/OpenTTD/dibridge) as well.

That way, malicious software would not be imposed on those interested in interacting with the community, and it would allow those who are trapped in Discord to break free from the restrictive platform.

Moreover, a bridge solution would not force any of the oppressed users to move away from the restrictive platform.

Thank you very much for your consideration.

### How to reproduce

The issue is Discord:
A reproduction of Discord as it is, is not required - and definitely not wanted.

### Crash reports, logs, images, videos

<img width="945" alt="Bildschirmfoto 2023-10-23 um 17 22 34" src="https://github.com/hyprwm/Hyprland/assets/16743943/83961418-f29d-435f-b8c8-99938470994d">

**Comment by tchofy** [comment]
Can't say much for everything else, but for the phone number issue it's stated the following in the rules channel:
![image](https://github.com/hyprwm/Hyprland/assets/64620317/2cab8a84-c9fa-4515-bb22-bf3cdd97f51a)

**Comment by vaxerski** [comment]
> I highly recommend [this Article on gnu.org](https://www.gnu.org/proprietary/proprietary.html) that explains the major issues with proprietary software

and I recommend using the search bar before opening an issue, as well as reading (ref: above by tchofy)

https://github.com/hyprwm/Hyprland/discussions/1307

**Comment by mariozupan** [comment]
What password I need to enter?

**Comment by gtristan** [comment]
+1.

I have been a GNOME contributor since 1999, maintainer of GTK+, Glade and evolution-data-server.

I have downright STOPPED any contributions due to the discontinuation of mailing lists.

I have tried hyprland and while it sucks as a DE (i.e. everything doesnt work, fingerprint login doesn't work with hyprlock, unlock takes *minutes*, lots of weird shit going on, everything needs to be coded, while I've got other things to code)... I would be HAPPY to help.

Either I can help by making GNOME accept your contributions, OR I can contribute to your project.

But if you DONT EVEN HAVE A MAILING LIST... the war is lost, where can I start, discord forums SUCK and are not a venue for centralized discussion of interested parties... there are exactly 9 people in your IRC channel... WHERE DO I GO TO HELP ???

**Comment by nilcrash** [comment]
The kids these days don't do email, mate.

You do have the self-awareness to understand your comment reads like "old man yells at cloud" right? :-)

I say this as an old man, with great respect and sensitivity to where you're coming from because I've had _the exact same thoughts_.

I know, we'd love it if we could make everyone conform to what we think is good and right and correct, but if you're not willing to meet the next generation, who is all about that discord/twitch life (hell, I don't even know what else they do now? light anime porn mixed with minecraft?), halfway then you're self-selecting yourself out of being a contributor to anything they want to work on.

Which sucks, because us old folk have tons of experience to bring to the game and maybe we can gently guide them on their journey from being scrappy youngsters to being old peeps with decades of experience behind them.

**Comment by izmyname** [comment]
Discord is cringe - that's for sure. Most of Hyprland dramas wouldn't have happened if not for the discord server.



> everything doesnt work, fingerprint login doesn't work with hyprlock, unlock takes _minutes_, lots of weird shit going on

You're too unspecific for someone claiming to have contributed to a big project. "Everything sucks" is not a feedback and you should know it.



> everything needs to be coded

Yup, that's true for every standalone wayland compositor/xorg wm.



> But if you DONT EVEN HAVE A MAILING LIST... the war is lost

The war against who? And why does your post look like one big title of a youtube CLICKBAIT video?
