### ISSUE TITLE
Diagonal screen tearing

### ISSUE THREAD

**Issue by NULL-BITS** [hyprwm/Hyprland#3725]
### Hyprland Version

hyprland-git-0.31.0.r7.a0b675ec-1

### Bug or Regression?

Bug

### Description

when using nvidia gpu applications have diagonal screen tearing link in this video.

https://sharex.host/iCqd9pSfZx.mp4?key=637976e852755c096c0e06dc0e9ea8

### How to reproduce

use nvidia driver 535.113.01

### Crash reports, logs, images, videos

https://sharex.host/iCqd9pSfZx.mp4?key=637976e852755c096c0e06dc0e9ea8

**Comment by vaxerski** [comment]
lmao nvidia moment

**Comment by zmeyka3310** [comment]
bump, its a multigpu issue, fixed by enabling vrr, reproducible by playing a game that has a fps cap lower than the framerate of the pc (facotrio, nier automata), however vrr causes fullscreen apps to freeze from time to time and also halves the maximum framerate for games, wich is a big issue for competitive fps games and lower refresh rate monitors

**Comment by NULL-BITS** [comment]
@zmeyka3310 even with vrr enabled the problem occures

**Comment by godm4352** [comment]
Lately I’ve been dealing with [diagonal screen tearing](https://xeniacanary.org/diagonal-screen-tearing/) in some of my apps and games, and it’s really frustrating. It’s different from the usual horizontal tearing and makes the visuals look jagged or split diagonally. Has anyone figured out what causes this or how to fix it?
