### ISSUE TITLE
Binded alt key for hotkeys triggers alt menu on apps

### ISSUE THREAD

**Issue by githubkuyaya** [hyprwm/Hyprland#3981]
### Hyprland Version

Hyprland, built from branch  at commit 1b48642fd15c433c53876f1b933dcd46265caf8f

### Bug or Regression?

Bug

### Description

If you bind the Alt Key for a shortcut, for example changing the keyboard layout, the keyboard shortcut triggers the Alt Menu on apps such as Firefox, Masterpdfeditor or QOwnNotes. As this does **not** happen when switching the keyboard layout via the input section `input { kb_options: grp:alt_shift_toggle }`, I would consider this a bug.

### How to reproduce

In your `hyprland.conf`, paste the following line:
```
bind = Alt, SHIFT_L, exec, hyprctl switchxkblayout at-translated-set-2-keyboard next
```
After saving the file, open Firefox and switch the keyboard layout via the alt and left shift key (normal `SHIFT` doesn't work as a bind for some reason?). The Alt Menu (File, Edit, History, View, etc...) will open. This prevent further typing until the alt key is pressed again, which is annoying.

Now, replace the line above with the following line:
```
input { kb_options: grp:alt_shift_toggle }
```
Redo the same steps and the Alt Menu will not open anymore. As the bind option would offer much more freedom (e.g. invoke additional script that updates an eww bar), it would be awesome to be able to use said option as well without having it trigger the Alt Menu on apps that support it.

**Comment by vaxerski** [comment]
what if you `bindr=ALTSHIFT, SHIFT_L, exec, ...`

**Comment by githubkuyaya** [comment]
> what if you `bindr=ALTSHIFT, SHIFT_L, exec, ...`

Unfortunately, this doesn't seem to execute any action for me. The following options don't execute the command after `exec`:
```
bind = Alt, SHIFT, exec, ...
bind=ALTSHIFT, SHIFT, exec, ...
bind=ALTSHIFT, SHIFT_L, exec, ...
bindr = Alt, SHIFT, exec, ...
bindr = Alt, SHIFT_L, exec, ...
bindr=ALTSHIFT, SHIFT, exec, ...
bindr=ALTSHIFT, SHIFT_L, exec, ...
```
For me, only this combination executes anything (whether or not it triggers the alt menu):
```
bind = Alt, SHIFT_L, exec, ...
```

**Comment by vailrahmatulin** [comment]
I figured out what the problem was. The fact is that in your SwitchKeyboardLayout script.sh is used by at-translated-set-2-keyboard. This is not a universal solution when connecting multiple keyboards. Accordingly, your script Processes several layouts, but only for one keyboard. In my case, it's a laptop keyboard. The script does not work on an external USB keyboard. When I clicked on the widget, the layout on the laptop keyboard changed, and I continued to type on the external one. I fixed the script SwitchKeyboardLayout.sh now it changes the layout on all connected keyboards.

```
#!/bin/bash
# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  ##
# This is for changing kb_layouts. Set kb_layouts in $settings_file

layout_f="$HOME/.cache/kb_layout"
settings_file="$HOME/.config/hypr/UserConfigs/UserSettings.conf"
notif="$HOME/.config/swaync/images/bell.png"

# Check if ~/.cache/kb_layout exists and create it with a default layout from Settings.conf if not found
if [ ! -f "$layout_f" ]; then
  default_layout=$(grep 'kb_layout=' "$settings_file" | cut -d '=' -f 2 | cut -d ',' -f 1 2>/dev/null)
  if [ -z "$default_layout" ]; then
    default_layout="us" # Default to 'us' layout if Settings.conf or 'kb_layout' is not found
  fi
  echo "$default_layout" > "$layout_f"
fi

current_layout=$(cat "$layout_f")

# Read keyboard layout settings from Settings.conf
if [ -f "$settings_file" ]; then
  kb_layout_line=$(grep 'kb_layout=' "$settings_file" | cut -d '=' -f 2)
  IFS=',' read -ra layout_mapping <<< "$kb_layout_line"
fi

layout_count=${#layout_mapping[@]}

# Find the index of the current layout in the mapping
for ((i = 0; i < layout_count; i++)); do
  if [ "$current_layout" == "${layout_mapping[i]}" ]; then
    current_index=$i
    break
  fi
done

# Calculate the index of the next layout
next_index=$(( (current_index + 1) % layout_count ))
new_layout="${layout_mapping[next_index]}"

# Update the keyboard layout
hyprctl switchxkblayout "at-translated-set-2-keyboard" "$new_layout"
echo "$new_layout" > "$layout_f"

# Notification for the new keyboard layout
#notify-send -u low -i "$notif" "new KB_Layout: $new_layout"


# Created by T-Crypt

get_keyboard_names() {
    hyprctl devices -j | jq -r '.keyboards[].name'
}

change_layout() {
    local got_error=false

    while read -r name; do
        hyprctl switchxkblayout "$name" next
        if [[ $? -eq 0 ]]; then
            echo "Switched the layout for $name."
        else
            >&2 echo "Error while switching the layout for $name."
            got_error=true
        fi
    done <<< "$(get_keyboard_names)"

    if [ "$got_error" = true ]; then
        >&2 echo "Some errors were found during the process..."
        return 1
    fi

    return 0 # All layouts had been cycled successfully
}

if ! change_layout; then
    notify-send -u low -t 2000 'Keyboard layout' 'Error: Layout change failed'
    >&2 echo "Layout change failed."
    exit 1
else
    #notify-send -u low -t 2000 'Keyboard layout' 'Current Layout Changed'
	notify-send -u low -i "$notif" "new KB_Layout: $new_layout"
    #echo "Layout change successful."
fi
```
I took the second part of the script from here: [T-Crypt](https://github.com/T-Crypt/hyprland-layoutswitch
)
For the widget to work correctly, it is necessary in the UserSettings.conf file in the input section of the 
```
 kb_variant=
 kb_model=
 kb_options=
 kb_rules=
```
 leave empty
And insert a line 
`bindn = ALT_L, SHIFT_L, exec, $scriptsDir/SwitchKeyboardLayout.sh `
in the file UserKeybinds.conf 
After that, the script will be called when you press Alt+Shift. Note that the `bindn` command is used, this is not a typo, as far as I understand, this is done so that application menus are not called, for example in Firefox.

Sorry again for my English. If something is difficult to understand, do not hesitate to ask, I will try to help.
