### ISSUE TITLE
Browser text/image distorts  when moving / resizing (Brave only)

### ISSUE THREAD

**Issue by salimp2009** [hyprwm/Hyprland#4099]
### Hyprland Version

hyprland-git  0.33.1.r12.dd0714c2-1 

### Bug or Regression?

Bug

### Description

I just updated Hyprland and when I move the windows (browser) around / resize  the text or graphics of the browser being distorted & larger. 

it was not happening before the update.

 I am on hyprland-git  0.33.1.r12.dd0714c2-1 . 

it happens to the browser only (Brave only) and it does not happen all the time. 
the link to video is attached.
https://www.twitch.tv/videos/1999339987

this seems to be happening to Brave only (Firefox OK) but it happens only on Hyprland and started after the update. I have Gnome Wayland on laptop, it does not happen there .

I am on Arch, latest kernel  6.6.4-arch1-1 ; GPU driver: nvidia-dkms 545.29.06-1 

in case needed my coınfig is here
https://github.com/salimp2009/deskmach_config/blob/main/hypr/.config/hypr/hyprland.conf

### How to reproduce

- update Hyprland
-  just open Brave browser , move around or resize 

### Crash reports, logs, images, videos

https://www.twitch.tv/videos/1999339987

**Comment by ArtemSmaznov** [comment]
I am quite sure I have been having the same behavior all this time and didn't even think of it as a bug.

I do not remember seeing this on window move, but multiple apps do this when resized (like opening a new window next to it or moving to another monitor, etc.). Quite sure I have seen this with Qutebrowser and Emacs, maybe others... As I said I never payed it any mind. I always though it was just my hardware struggling to update the graphics of the window straight away and was just stretching, compressing it like it was a static image until eventually updating to normal. And I bet this happens with every resize for everyone, just takes a millisecond to update so it is not observable.

For me it is usually instant as well but sometimes it will take like 1-2 seconds to update. Much rarer it will take 5-10 sec.

I am currently on 
hyprland-git v0.32.3-105-g80b9b21f (as I said quite sure I had this since forever)
nvidia-dkms 535.113.01
arch-zen 6.6.4

**Comment by salimp2009** [comment]
@ArtemSmaznov I never had this issue before since I have been on Wayland almost a year. And it is kinda specific to Brave only. Does not happen to any apps or even FireFox works normal. Only Brave after the update. I have same Brave version on Gnome wayland and it does not happen there but it is not fair to compare Gnome to a compositor I guess. it working fine since last week

**Comment by vaxerski** [comment]
#1462

**Comment by salimp2009** [comment]
Just FYI; #1462 issues are older. this one just happened recently. I have been using Brave almost a year and had no issues until yesterday. So the changes between last saturday and yesterday might have caused this behaviour.

**Comment by vaxerski** [comment]
umm, no, this has been happening forever.

**Comment by salimp2009** [comment]
> umm, no, this has been happening forever.

Weird. i have been using Brave for almost a year on Hyprland and never had that problem.
but I was on the hyprland-nvidia-git package until it became unnecessary. 

I switched to hyprland-git 2 weeks ago i guess whenever it was good for nvidia and it was still working. 
I wonder and did not have it until yesterday :) That is really weird.

**Comment by salimp2009** [comment]
and here is kinda proof that it was working even 7 months ago ; i always test OBS after updates :)
https://www.twitch.tv/videos/1813792522

**Comment by vaxerski** [comment]
you are wrong idk it's been like this forever

**Comment by ArtemSmaznov** [comment]
Putting history aside this did make me think whether this can actually be improved? Probably only after Wayland is way more mature as a whole, but can it?

**Comment by vaxerski** [comment]
IIRC this is a chromium issue, or was last time I tested it.
