### ISSUE TITLE
Window decorations get rendered for fullscreen windows

### ISSUE THREAD

**Issue by alba4k** [hyprwm/Hyprland#4117]
### Hyprland Version

`Hyprland, built from branch main at commit efdf07e295d00cf5391a8c0089967a69a76d9b08 dirty (renderer: Allocate background texture only if required (4111)). Tag: v0.33.1-20-gefdf07e2`

### Bug or Regression?

Regression

### Description

Window borders are still rendered for fullscreen windows.

This can be noticed when using rounded corners or when switching to an other workspace using 1:1 gestures.

### How to reproduce

1. Make a window fullscreen
2. Look at the window corners

### Crash reports, logs, images, videos

![immagine](https://github.com/hyprwm/Hyprland/assets/84153269/69c3538d-07e8-469c-975a-32f585f9e58c)

![immagine](https://github.com/hyprwm/Hyprland/assets/84153269/e9fbadba-43ee-49c7-b873-94d6cb3698cf)

**Comment by cprin21** [comment]
Noticed this issue as well, showing in fullscreen games too. Thanks for reporting!

**Comment by phonetic112** [comment]
`windowrulev2 = rounding 0, fullscreen:1` use for now

**Comment by cprin21** [comment]
> `windowrulev2 = rounding 0, fullscreen:1`

Thank you! Not just using that for now but it's a good thing to set and forget, because why would we want any rounding when we want the application to be fullscreen anyhow

**Comment by alba4k** [comment]
> `windowrulev2 = rounding 0, fullscreen:1` use for now

Maybe add `windowrulev2 = noborder, fullscreen:1` to fix whats shown in the second pic

**Comment by Gaugeforever** [comment]
This is for anyone who comes here because some games through proton start as not floating but also not fullscreen.  Normally, inside a game you can set fullscreen and it works fine.  However, some applications, and games, require a restart.  These applications seem to not work with hyprland well. 

While the application is running you can type `hyprctl clients` into a terminal.  With the output you can get the title of your game.  Inside of your hyprland config put the following  `windowrulev2 = fullscreen, title:^(App Title)$`.  This will cause the game to open correctly.  You should also run all games in fullscreen windowed mode where possible to prevent the black screen issue.

Another solution is to bind a fullscreen toggle.  You can do this in your hyprland config by putting in `bind = $mainMod, F, fullscreen`.  I hope this helps someone.  I'm not sure what the issue is with specific games through proton.
