### ISSUE TITLE
Running  Games on Hyprland With Nvidia Drivers has a Black Flicker

### ISSUE THREAD

**Issue by danielbyomujuni** [hyprwm/Hyprland#4138]
Preface: Yes I do understand that NVIDIA on Hyprland is not supported entirely.  

## Hyprland Version

Hyprland, built from branch HEAD at commit ba2af6f86d26fbf4b51aa37bf901e0118f46bbe3 \
on December 12 2023

### Other Hyprland Versions Tried

[AUR] Hyperland-Nvidia-git: December 11, 2023 \
[AUR] Hyperland-Nvidia: December 11, 2023 \
[AUR] Hyperland-git: December 11, 2023 \
[extra] Hyperland: December 11, 2023 

## Bug or Regression?

Bug

## Description

When playing Games They Flicker black
They game automaticly Run Xwayland

Ive tested 3 Game \
    - Minecraft \
    - Lethal Company \
    - Warframe \
    all exibit the same Issue

## Steps to Reproduces

    - Install Arch Linux w/ hyprland
    - Install and setup the NVIDIA Proietry Drivers
    - Setup up the Hyprland Config & app Tearing for Specified Game to the window rules
    - Install and Run a Game
    - Get into actual gameplay
    - and there

## Steps done to try and resolve
    - Try diffrent distrobutions of Hyprland
    - Try Downgrading the Graphics Drivers
    - Swapping my Kernal from linux-lts to linux
    - Swapping Nvidia driver from nvidia-lts to nvidia 
    - Adjusting Setting for tearing in the hyprland.conf

    -Testing to see if the issue could be replicated in the Wayland session of KDE Plasma (Issue was not present).

## Relevent Files

!! Warning Flashing Lights !! \
[Video of Issue](https://youtu.be/g-IST1pSCqM)

[My Hyprland.conf](https://github.com/danielbyomujuni/dot-files/blob/master/hypr/hyprland.conf)

**Comment by vaxerski** [comment]
> Yes I do understand that NVIDIA on Hyprland is not supported entirely.

then why open? It's not supported at all.

Could be lack of explicit sync, could be nvidia being nvidia, could be https://wiki.hyprland.org/Nvidia/#fixing-random-flickering-nuclear-method

No clue.

**Comment by jones-josh** [comment]
Same issue with my setup. I've tried the steps you mentioned and more, with the only workaround being lowering the refresh rate of the monitors. If you want to continue using hyprland on your nvidia setup, the issue ceased for me at 60fps, but do try different values. Unfortunately I will not be using hyprland until I own an AMD GPU as result.

Not something that will be fixed, but should be kept in mind for people wishing to migrate to hyprland, and I might make a PR on the docs adding to the existing warning of lack of support.

**Comment by Fxzzi** [comment]
NVidia Drivers 545 and onward, including 550 in some cases, has flickering with XWayland, mostly games. To hopefully resolve this, please try downgrading all nvidia packages to their latest 535xx version. This can be done with the AUR packages with 535xx in its name. https://aur.archlinux.org/packages?O=0&K=535xx

p.s. It seems to be a common misconception that nvidia-lts is an lts version of the nvidia driver, however this is not the case. It is still the same version as the nvidia driver, just built against the lts kernel. nvidia works with `linux`, nvidia-lts works with `linux-lts`

another p.s. Minecraft versions past 1.19 or so can be made to run with Wayland instead of XWayland. Here is a reddit post with more info: https://www.reddit.com/r/linux_gaming/comments/18r8x22/minecraft_running_purely_on_wayland_without/
This would solve the flickering on Minecraft.

**Comment by jones-josh** [comment]
@Fxzzi thank you kindly, this did resolve it for me entirely. Will still be changing GPU as soon as I can though.

**Comment by jones-josh** [comment]
[PR is open ](https://github.com/hyprwm/hyprland-wiki/pull/449)to add above to Hyprland wiki

**Comment by jones-josh** [comment]
Apologies for spam, but [according to nvidia dev amrits](https://forums.developer.nvidia.com/t/545-drivers-have-bad-flickering-and-black-screen-issues-when-vrr-is-enabled/269801/34) this has been fixed, and will be released hopefully soon
