### ISSUE TITLE
Can't get the right refresh rate on my displays

### ISSUE THREAD

**Issue by Myvillithdar** [hyprwm/Hyprland#4139]
### Hyprland Version

Hyprland, built from branch HEAD at commit d74607e414dcd16911089a6d4b6aeb661c880923  (props: bump ver to 0.33.1).

### Bug or Regression?

Bug

### Description

I have two 4k TVs connected to my machine.  Both of them are capable of 3840x2160 @ 59.94Hz, and Xorg and Windows are both happy to run them at that mode (though it defaults to 30Hz), but under wayland I can't get them to run higher than 30Hz.  I've tried setting a custom modeline in hyprland.conf, and that makes the mode show up in wlr-randr but it keeps using the 30Hz mode anyway.  I've tried the `--custom-mode` argument in wlr-randr, too, but that doesn't do anything.

### How to reproduce

The devices I'm having trouble with are a Samsung TV and an RCA Roku TV.  I'm guessing any budget 4k 60Hz TV would have a good chance of reproducing this issue.  (There's also a 1080p screen connected to this computer, but I'm guessing that's not relevant)

### Crash reports, logs, images, videos

`hwinfo --monitor`: [hwinfo-output.txt](https://github.com/hyprwm/Hyprland/files/13652275/hwinfo-output.txt)
`hyprctl monitors`: [hyprctl-monitors-output.txt](https://github.com/hyprwm/Hyprland/files/13652276/hyprctl-monitors-output.txt)
`wlr-randr`: [wlr-randr-output.txt](https://github.com/hyprwm/Hyprland/files/13652277/wlr-randr-output.txt)
`xrandr`: [xrandr-output.txt](https://github.com/hyprwm/Hyprland/files/13652278/xrandr-output.txt) (this is from running xrandr in i3, not xwayland)

**Comment by vaxerski** [comment]
thats a wlroots issue

**Comment by Myvillithdar** [comment]
guess I'll open an issue there, then.  thanks for pointing me in a direction

**Comment by squeaktoy** [comment]
So I was just in the #wlroots IRC channel and they asked me to go to my compositor's channel. Well, here I am...

**Comment by Myvillithdar** [comment]
@squeaktoy for what it's worth, the wlroots folks [told me](https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3785) that this issue was actually due to the kernel-space graphics drivers.  I ended up switching back to xorg for unrelated reasons, so I never got around to opening another issue there

**Comment by squeaktoy** [comment]
You also have NVIDIA just like me, so I wonder if this only applies to NVIDIA and not to AMD. Believe it or not, but Sway turns out to be a lot buggier than Hyprland is on NVIDIA. The only thing on Hyprland that makes me not want to further use it is that it won't listen to my wlr-randr commands to try to switch to the custom mode I made in the config. Sway has a lot of weird graphical artifacts and glitches, and refuses to output anything to the screen when trying to apply a custom mode. If anyone has an AMD card and a display that doesn't have official EDD for high refresh rates (but can be 'overclocked' to higher rates), can you try putting this (or equivalent for your monitor) in your config?:
```
monitor=HDMI-A-1, modeline 333.22 1920 1928 1960 2000 1080 1143 1151 1157 +hsync -vsync, auto, 1
```
I wonder if it will apply when Hyprland launches or if it will revert back to 60 Hz like it did for me.
Then try the following command (or equivalent):
```
wlr-randr --output HDMI-A-1 --mode 1920x1080@144.001999Hz
```
and try running `wlr-randr` again. In my case it doesn't change the mode at all. It stays on 60 Hz. I wonder what the behaviour is for others who do have an AMD card.
