### ISSUE TITLE
hyprpm loads plugin after it's needed by other loading steps

### ISSUE THREAD

**Issue by Pieterv24** [hyprwm/Hyprland#4144]
### Hyprland Version

v0.33.1-37-g4190b967

### Bug or Regression?

Bug

### Description

When loading a plugin by enabling it with 'hyprpm', an error is thrown by Hyprland that it cannot find the layout and directives included in the plugin.
Running hyprctl after loading Hyprland fixes the error.

hyprctl plugins list returns the plugin as loaded correctly.

When disabling the plugin using hyprpm and loading it directly in the config when by using:
'plugin = /home/<user>/.local/share/hyprpm/hy3/hy3.so' 
Fixes the issue.

My suspicion is that when using hyprpm, the plugin is loaded at a later stage then the bind and layout settings in the Hyprland.conf are evaluated.
While when using the plugin entry in the config file, this is evaluated before the bind and layout settings are evaluated. 

### How to reproduce

install a plugin using hyprpm. (in my case I've used hy3).
- `hyprpm add https://github.com/outfoxxed/hy3`
enable the plugin
- `hyprpm enable hy3`

use the hy3:makegroup or any of the hy3 directives with a keybind.

restart Hyprland (preferably a cold boot).

You should get an error that an error occured while starting Hyprland and that the directive hy3:makegroup could not be found.

When using the hy3 layout, you can also see in the logs that Hyprland is unable to find the layout.

Running `hyprctl reload` should fix this error.

**Comment by zakk4223** [comment]
If you use 'plugin =' in the config, hyprland loads all the plugins after it parses the config, and then does a force reload of the config immediately after.

Loading plugins 'externally' (including via hyprpm) doesn't force a config reload unless the plugin itself triggers a reload. It looks like hy3 doesn't do that, so the config doesn't get reloaded until you otherwise force it.

Maybe hyprpm should issue a config reload after all plugins are loaded.

**Comment by vaxerski** [comment]
> Maybe hyprpm should issue a config reload after all plugins are loaded.

it should, that's what I show in the example config, even.
