### ISSUE TITLE
hypr 0.34 broke monitor fractional scaling

### ISSUE THREAD

**Issue by ilyss01** [hyprwm/Hyprland#4337]
### Hyprland Version

```sh
Hyprland, built from branch HEAD at commit 03ebbe18ed8517ee22591eac82cd54322f42cb7d  (props: bump ver to 0.34.0).
Date: Mon Jan 1 12:03:15 2024
Tag: v0.34.0

flags: (if any)
```

### Bug or Regression?

Bug

### Description

Before update I used this setup:
```sh
monitor = HDMI-A-2, preferred, 0x0, auto
monitor = eDP-1, preferred, 1922x0, 1.1
```

After 0.34.0 I constantly getting this message:
![image](https://github.com/hyprwm/Hyprland/assets/47274578/6215d684-9bda-417f-bf02-f5f05d55e4c0)

### How to reproduce

Write: 
```sh
monitor = eDP-1, preferred, 1922x0, 1.1
```
in your config file

### Crash reports, logs, images, videos

[hyprland.log](https://github.com/hyprwm/Hyprland/files/13820446/hyprland.log)

**Comment by fufexan** [comment]
It is not a bug. The fractional scaling handling has been changed to be a fraction \<numerator>/120 = \<scale>.

**Comment by vaxerski** [comment]
additionally it has to divide your resolution without fractions

**Comment by GOKOP** [comment]
> additionally it has to divide your resolution without fractions

Why? I had the scale set to 1.13 which I calculated based on my DPI. After this change my closest options seem to be 1 or 1.25, and neither satisfies me.

**Comment by vaxerski** [comment]
because otherwise you get pixel rounding errors

**Comment by thejch** [comment]
> Why? I had the scale set to 1.13 which I calculated based on my DPI. After this change my closest options seem to be 1 or 1.25, and neither satisfies me.

hack: `debug:disable_scale_checks = true`

**Comment by GOKOP** [comment]
> because otherwise you get pixel rounding errors

You mean like one pixel getting rounded one way and another getting rounded the other way or something more severe? Because if it's just that then sure I've noticed it (rarely) but it didn't bother me too much

@thejch Thanks! I was gonna suggest adding an option to disable this limitation that comes with some warning about possible issues, turns out it's already there

**Comment by pguimier** [comment]
I think it's a regression, because in previous versions it was possible and without pixel rounding errors. 
I scripted a down/up zoom with shortcuts stepped by 0.1 and it worked like a charm..
Now, using `debug:disable_scale_checks = true` (thanks @thejch) the image is incomplete with lot of errors.

**Comment by pguimier** [comment]
> I think it's a regression, because in previous versions it was possible and without pixel rounding errors. I scripted a down/up zoom with shortcuts stepped by 0.1 and it worked like a charm.. Now, using `debug:disable_scale_checks = true` (thanks @thejch) the image is incomplete with lot of errors.

Well, the last version (0.35.0-2) resolves the problem, even if the error message appears if the debug instruction is commented, no more pixel rounding error. HUGE THANKS !
