### ISSUE TITLE
JetBrains XWayland crash when moving cursor fast over menu/quick items 

### ISSUE THREAD

**Issue by romanstingler** [hyprwm/Hyprland#4396]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 7e033e48ace5406a9bc442f7d403f9ce3af193f3 dirty (make: unbreak with non-GNU ln(1) after 78f9ba9fdd7e).


```

</details>

### Bug or Regression?

Bug

### Description

I know, I know, XWayland of JetBrains is bad, but crashes shouldn't happen. 

[hyprlandCrashReport1794.txt](https://github.com/hyprwm/Hyprland/files/13872302/hyprlandCrashReport1794.txt)

### How to reproduce

when moving the cursor fast over the menu items 
![image](https://github.com/hyprwm/Hyprland/assets/5576250/0e852e0e-e55e-448e-be4b-d5fc25d41a4b)
hyprland begins to stutter and at some point it just crashes

**Comment by namaek2** [comment]
Same happens on my Jetbrain IDEs. It's really annoying.
When I put my cursor on side menus, it flickers really fast and IDE goes crash with not normal memory consumption.
And also cursor doesn't work accurately on pop-up menus. it picks wrong pos

I'm using 4k HiDPi, GTK_SCALE=2, and 125% appearance on IDE.

**Comment by shauser** [comment]
The problem seems to have to do with the tooltip windows. Every action which has a tooltip creates a tooltip window which seems to be immediately closed again. The waybar window indicator switches between the IDE and win1234 with the number increasing on each frame.

**Comment by PoltyPoltou** [comment]
There are related issues that were opened on the subject : #2245 and #4257. It was fixed but other fixes broke it so it seems hard to maintain specific apps that are bad in xwayland.

The workaround that fixed lots of my issues with jetbrains IDE (tooltips that go crazy and the switcher not closing):

> Thanks to [#2315 (comment)](https://github.com/hyprwm/Hyprland/issues/2315#issuecomment-1555896701) it solved my issue with version v0.34.0 !
> 
> The workaround is to add `windowrulev2 = noinitialfocus,class:^jetbrains-(?!toolbox),floating:1` to your config.

I hope it can help you.

**Comment by saswatax** [comment]
try this
```
windowrulev2 = windowdance, class:^(.*jetbrains.*)$
windowrulev2 = noinitialfocus, class:^(.*jetbrains.*)$, title:^(win.*)$
windowrulev2 = nofocus, class:^(.*jetbrains.*)$, title:^(win.*)$
````

**Comment by vaxerski** [comment]
can I get an ASan trace from this? https://wiki.hyprland.org/Crashes-and-Bugs/#building-the-wayland-stack-with-asan

**Comment by danilo-alm** [comment]
same happening with me. Adding `windowrulev2 = noinitialfocus,class:^jetbrains-(?!toolbox),floating:1` to the config did not fix it

https://github.com/hyprwm/Hyprland/assets/88722240/b87996c7-da6b-4841-85fa-f14b788a56ad

**Comment by vaxerski** [comment]
that is not an asan trace

**Comment by danilo-alm** [comment]
> that is not an asan trace

Sorry, I didn't even see your comment. Can you inform me if it takes long to build Wayland and Hyprland? I have a laptop with a Ryzen 5 5500U, no GPU, and didn't want to start it and have to stop it because I needed to take my laptop somewhere.

**Comment by JettScythe** [comment]
> try this
> 
> ```
> windowrulev2 = windowdance, class:^(.*jetbrains.*)$
> windowrulev2 = noinitialfocus, class:^(.*jetbrains.*)$, title:^(win.*)$
> windowrulev2 = nofocus, class:^(.*jetbrains.*)$, title:^(win.*)$
> ```

works for me. Thank you! I never had hyprland crash as others have, but the flickering and need to buttonmash to get any of  those windows open was driving me mad.

**Comment by Nyayurn** [comment]
> works for me. Thank you! I never had hyprland crash as others have, but the flickering and need to buttonmash to get any of those windows open was driving me mad.

It's work, but a new issue has arisen, I can't drag sidebar icon

https://github.com/hyprwm/Hyprland/assets/132195516/c8738651-8014-4f73-b23e-80b468dc04e2

**Comment by MightyPlaza** [comment]
JetBrains IDE's now have [experimental Wayland support](https://blog.jetbrains.com/platform/2024/07/wayland-support-preview-in-2024-2/)
Please try the versions in their Early Acess Program and see if they fix this issue.
Relevant Download links:
https://www.jetbrains.com/idea/nextversion/
https://www.jetbrains.com/pycharm/nextversion/
https://www.jetbrains.com/go/nextversion/

that and maybe this has been fixed by the rewrites

**Comment by Nikolai2038** [comment]
I encountered simular issue in Hyprland with WebStorm running in `Xwayland` (happens in other JetBrains IDEs too). When selecting text by mouse cursor in the terminal or in the commit message editor, the `Hyprland` process will start consuming 100% CPU, and then crash. `Hyprland` command ends with:

```plaintext
error marshalling arguments for send: dup failed: Too many open files
error in client communication (pid 30820)
file descriptor expected, object (44), message add(huuuuu)
error in client communication (pid 30767)
XWAYLAND: wl_display#1: error 1: invalid arguments for zwp_linux_buffer_params_v1#44.add
(EE) failed to dispatch Wayland events: Invalid argument
```

So I assume it probably starts to open ton of invisible tool windows and [run out of file descriptors](https://www.baeldung.com/linux/error-too-many-open-files) (because [lowering `fs.file-max` value](https://github.com/hyprwm/Hyprland/issues/6323) from default `9223372036854775807` makes the crash faster).

I was able to fix this by installing and enabling `xwayland-satellite`, because found related [`invalid arguments for zwp_linux_buffer_params_v1` issue](https://github.com/Supreeeme/xwayland-satellite/issues/144).

```sh
sudo pacman --noconfirm --sync --refresh --needed xwayland-satellite && \
systemctl --user enable --now xwayland-satellite.service
```

(then relogin or reboot needed I think)

Enabling experimental Wayland support via adding `-Dawt.toolkit.name=WLToolkit` to `.vmoptions` file bring this issue back, so I will stick to `Xwayland` for now.

My current versions:

```sh
webstorm --version && Hyprland --version
```

```plaintext
WebStorm 2025.2 EAP
Build #WS-252.21735.34

Hyprland 0.49.0 built from branch  at commit 9958d297641b5c84dcff93f9039d80a5ad37ab00  (version: bump to 0.49.0).
Date: Thu May 8 20:15:18 2025
Tag: v0.49.0, commits: 6098
built against:
 aquamarine 0.8.0
 hyprlang 0.6.3
 hyprutils 0.7.1
 hyprcursor 0.1.12
 hyprgraphics 0.1.3
no flags were set
```

Update:
- For me, the problem was actually caused by running `wl-clip-persist --clipboard both &` instead of `wl-clip-persist --clipboard regular &`
