### ISSUE TITLE
Nvidia env variable problem

### ISSUE THREAD

**Issue by mshzsh** [hyprwm/Hyprland#4511]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 03ebbe18ed8517ee22591eac82cd54322f42cb7d  (props: bump ver to 0.34.0).
Date: Mon Jan 1 12:03:15 2024
Tag: v0.34.0

flags: (if any)
```

</details>

### Bug or Regression?

Bug

### Description

Distro: Arch
Kernel: 6.7.0-arch3-1
GPU: Nvidia 970m

When i add `env=__GLX_VENDOR_LIBRARY_NAME,nvidia` in hyprland.conf, the vscode lags a lot!
Also when i add `env=GBM_BACKEND,nvidia-drm` , Firefox crashes when opening some websites.

### How to reproduce

You need a system with Nvidia GPU and use nvidia drm.
Then add mentioned env variables and after that use vscode and open Firefox then go to the for example (time.ir) website.

**Comment by archdron** [comment]
Did you do everything according to the wiki? I.e., [wrapping the launcher](https://wiki.hyprland.org/0.19.2beta/Getting-Started/Quick-start/#wrapping-the-launcher-recommended), [installing nvidia-dkms](https://wiki.hyprland.org/Nvidia/#how-to-get-hyprland-to-possibly-work-on-nvidia) instead of plain nvidia driver?
I have none of the problems with VS Code and Firefox that you described.

Distro: Arch
Kernel: 6.7.0-arch3-1
GPU: Nvidia GTX 1660 Ti Mobile

**Comment by vaxerski** [comment]
nvidia is not officially supported
