### ISSUE TITLE
9f20a15 Introduces subtle stuttering when moving floating windows

### ISSUE THREAD

**Issue by burein-ita** [hyprwm/Hyprland#4542]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 8b1069b33051dbc3a133444dc6ce7385cdc51377 dirty (flake.lock: update).
Date: Sat Jan 27 09:31:39 2024
Tag: v0.34.0-68-g8b1069b3

flags: (if any)


System Information:
System name: Linux
Node name: zombie
Release: 6.7.1-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Sun, 21 Jan 2024 22:14:10 +0000


GPU information:
0000:00:02.0 VGA compatible controller [0300]: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] [8086:9a49] (rev 01) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Regression

### Description

9f20a15955697b0f52740c1e0180acdafa071f79 introduces subtle stutter/jitter(?) when moving a floating window.

Reverting that commit fixes the issue.

### How to reproduce

\> build latest
\> make a window float
\> move it around
\> stutters subtly
\> die of embarrassment

**Comment by Sinaaaa** [comment]
It's possible this is the causing insane all around lag on my system, no need to float anything, just move mouse or try to start Alacritty.. It's a literal slideshow.

**Comment by Saltyc0der** [comment]
I'm having pretty bad lag too. Same build as OP, running Intel Arc dgpu.

**Comment by Sinaaaa** [comment]
> edit: latest commit fixes it for me

It's fixed for me as well.

**Comment by bvr-yr** [comment]
@Sinaaaa @Saltyc0der your issues are unrelated to this

https://github.com/hyprwm/Hyprland/commit/9f20a15955697b0f52740c1e0180acdafa071f79 indeed introduced this regression

@burein-ita i suppose u are on laptop, what is your refresh rate?
i can assume it's 60hz


i have same issue on builtin 60hz laptop display, plugging in 120hz external display fixes it, moving or resizing windows on builtin display are smooth again
same if u run hyprland nested on WL-1@120hz

i assume this happens because resize limiter doesn't return in those cases, while after 9f20a15 it returns almost always on `g_pHyprRenderer->m_pMostHzMonitor->refreshRate` = 60

also removing `(*PANIMATEMOUSE || *PANIMATE)` makes moving/resizing too sluggy in case these options are enabled, but this may be because i'm on HASWELL (10y.o.)

**Comment by burein-ita** [comment]
@bvr-yr Yes 60hz display.

**Comment by bvr-yr** [comment]
@burein-ita what mouse do u use?

**Comment by burein-ita** [comment]
@bvr-yr This model: https://icecat.biz/p/hp/xq500aa-abb/mice-xq500aa-16668214.html

**Comment by erroor234** [comment]
Also lags on Artix Linux / hyprland 0.35.0-2 / any kernel (lts, default, zen) / nvidia-dkms when moving windows (no matter xwayland or native wayland)
