### ISSUE TITLE
My screen goes black and nothing works have to force restart "sometimes" when i open my laptop's lid after break(suspended state of laptop)

### ISSUE THREAD

**Issue by HakaishinShwet** [hyprwm/Hyprland#4578]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit d9b74ff96b3e3f0341a386451b9a3375b6f05503 dirty (renderer: staticize local functions).
Date: Tue Dec 19 17:25:56 2023
Tag: v0.33.1-60-gd9b74ff9

flags: (if any)
debug

```

</details>

### Bug or Regression?

Bug

### Description

My screen goes black and nothing works have to force restart "sometimes" when i open my laptop's lid after break(suspended state of laptop) . but sometimes it works fine idk why but it is happening since many months but today i thought to finally create issue for this bug

### How to reproduce

i have hp pavillion laptop with 0.33 hyprland and this bug is not new and is happening with me since 8-9 months :-) so what can i say

**Comment by zenzoa** [comment]
I've had the same thing start happening to me recently - though I'm not 100% sure it's a Hyprland thing, since it started happening after updating my whole Arch Linux system. Running on a Framework 12th Gen laptop, with the package hyprland-0.34.0-1.

I'm able to wake my computer successfully after running `systemctl suspend,` and swayidle works with the config set to `timeout 300 'chayang -d 10 && hyprctl dispatch dpms off' resume 'hyprctl dispatch dpms on'`. Also when I open my laptop and the screen stays black, I seem to be able to use my normal set of keyboard commands to reboot (meta+esc brings up a logout/shutdown menu, arrow down to select "reboot" from the menu, enter to activate), suggesting that everything *except* the screen has woken up successfully. Some terminal text shows up on the screen immediately after Hyprland/Wayland closes, and from then on out everything's back to normal through the reboot process.

**Comment by vaxerski** [comment]
try hyprland-git. Also, IIRC, kernel 6.7 has issues with amdgpu causing gpu resets (which we can't handle atm, waiting for wlroots)

**Comment by HakaishinShwet** [comment]
i am on hyprland git only just that i am on 0.33.1 and latest one is 0.34 in previous versions too i faced same thing unfortunately so i dont think just updating will fix plus i am on intel processor and endeavour os latest which is stable and based on arch

**Comment by zenzoa** [comment]
hyprland-git solved the issue for me!

**Comment by izmyname** [comment]
Pinging the op to check, whether the later updates fixed the problem for them.
