### ISSUE TITLE
add windowrule: corners 

### ISSUE THREAD

**Issue by vincentaxhe** [hyprwm/Hyprland#4946]
### Description

move [x] [y] work with static window size, put windows in four corners will handle windows which  size varies. also need to detect bar height.

**Comment by Ligthiago** [comment]
You can add `move onscreen 100% 0%` windowrule to move window to the upper right corner of the screen, respecting borders and exclusive layers area. I guess you figure out how to move windows to other corners yourself.

You can also do this manually with `movewindow u` + `movewindow r` dispatchers, bind it on `mod + arrow keys` or something, because it also work with tiled windows.

**Comment by vincentaxhe** [comment]
@Ligthiago thank u, that's an more universal design by importing 'onscreen' arg.
