### ISSUE TITLE
Program becomes blurry when moving from a lower resolution screen to higher resolution screen using keyboard shortcut

### ISSUE THREAD

**Issue by Zyuke** [hyprwm/Hyprland#4987]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0

flags: (if any)

```

</details>

### Bug or Regression?

Bug

### Description

My laptop is connected to an external monitor which has lower resolution. When I move applications from a workspace on the external monitor to a workspace on my laptop using a keybind (SUPER SHIFT Num), the application will look blurry. However, if I drag the application from the external monitor to my laptop monitor using mouse motion (Holding SUPER and drag), the application would look normal.

Here is the output from `hyprctl monitors`

```
Monitor eDP-1 (ID 0):
	3200x1800@59.98200 at 0x0
	description: Sharp Corporation 0x144A (eDP-1)
	make: Sharp Corporation
	model: 0x144A
	serial: 
	active workspace: 1 (1)
	special workspace: 0 ()
	reserved: 0 28 0 0
	scale: 2.00
	transform: 0
	focused: no
	dpmsStatus: 1
	vrr: 0
	activelyTearing: false

Monitor DP-1 (ID 1):
	2560x1440@59.95100 at 1600x0
	description: ASUSTek COMPUTER INC ROG XG27AQ M7LMQS027213 (DP-1 via HDMI)
	make: ASUSTek COMPUTER INC
	model: ROG XG27AQ
	serial: M7LMQS027213
	active workspace: 2 (2)
	special workspace: 0 ()
	reserved: 0 28 0 0
	scale: 1.00
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: 0
	activelyTearing: false
```

My monitor config in hyprland.conf:
```
monitor=desc:Sharp Corporation 0x144A,highres,auto,auto
monitor=,preferred,auto,1
```
the first one is my laptop monitor

### How to reproduce

Open any application in a lower resolution external monitor and use keyboard binding to move it to a higher resolution laptop monitor.

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/14502912/patch.txt)
how about this

**Comment by Zyuke** [comment]
> [patch.txt](https://github.com/hyprwm/Hyprland/files/14502912/patch.txt) how about this

Hi, how do I apply the patch if I installed Hyprland with pacman? Thanks

**Comment by tchofy** [comment]
You will need to compile manually, check http://wiki.hyprland.org/Getting-Started/Installation/#manual-manual-build, and apply the patch before building.

Firstly, to avoid issues of having "two" Hyprlands on your system I recommend uninstalling hyprland with pacman first, then proceed to building.

So in summary, git clone, cd into Hyprland folder, put patch.txt inside it, and do `patch -p1 < patch.txt`, now you  can proceed to build it with `make all && sudo make install`, after it's done log out, and log back in, you should now be running hyprland with the latest commit, and with that patch applied. Try replicating your issue, and report if it worked, changed behavior, or didn't work at all. Once you're done testing, you can uninstall the manually built Hyprland with `sudo make uninstall` from inside the cloned Hyprland folder, now you can reinstall with pacman.

Since you're running Hyprland from the arch repos, you'll likely have to wait until vaxry tags the next release and the arch maintainers update it on their repos (latest tag is 0.36.0, the one from arch repos is still 0.35.0), so you're free to keep running the manually built version until that happens.

Oh and you'll probably get errors on your config file since any version above 0.3.6 uses a slightly different syntax for certain things in the config file, I recommend reading [the release page](https://github.com/hyprwm/Hyprland/releases/tag/v0.36.0) to see what changed and what you'll need to modify on your config file.

**Comment by Zyuke** [comment]
> You will need to compile manually, check http://wiki.hyprland.org/Getting-Started/Installation/#manual-manual-build, and apply the patch before building.
> 
> Firstly, to avoid issues of having "two" Hyprlands on your system I recommend uninstalling hyprland with pacman first, then proceed to building.
> 
> So in summary, git clone, cd into Hyprland folder, put patch.txt inside it, and do `patch -p1 < patch.txt`, now you can proceed to build it with `make all && sudo make install`, after it's done log out, and log back in, you should now be running hyprland with the latest commit, and with that patch applied. Try replicating your issue, and report if it worked, changed behavior, or didn't work at all. Once you're done testing, you can uninstall the manually built Hyprland with `sudo make uninstall` from inside the cloned Hyprland folder, now you can reinstall with pacman.
> 
> Since you're running Hyprland from the arch repos, you'll likely have to wait until vaxry tags the next release and the arch maintainers update it on their repos (latest tag is 0.36.0, the one from arch repos is still 0.35.0), so you're free to keep running the manually built version until that happens.
> 
> Oh and you'll probably get errors on your config file since any version above 0.3.6 uses a slightly different syntax for certain things in the config file, I recommend reading [the release page](https://github.com/hyprwm/Hyprland/releases/tag/v0.36.0) to see what changed and what you'll need to modify on your config file.

Thank you! That was very helpful.

**Comment by Zyuke** [comment]
> [patch.txt](https://github.com/hyprwm/Hyprland/files/14502912/patch.txt) how about this

I applied the patch and it works now
