### ISSUE TITLE
Hyprland should draw shadows on all layers.

### ISSUE THREAD

**Issue by hhhorb** [hyprwm/Hyprland#5275]
No. Layers should style themselves.

_Originally posted by @vaxerski in https://github.com/hyprwm/Hyprland/issues/4470#issuecomment-1898388184_

**Comment by hhhorb** [comment]
Reopening. This is wrong. Hyprland is a compositing window manager, it should handle transparency, blur, animations... and shadows. This is not a styling issue, it is a compositor issue. Box-shadow workarounds per-layer are an ugly hack. Hyprland should provide a shadow for waybar, for mako and for a launcher (fuzzel, wofi, whatever). Tag this as "theme unification" or whatever.

BTW @ vaserski, awesome work, thank you.

**Comment by hhhorb** [comment]
From the Features list, the first item...

"All of the eyecandy: gradient borders, blur, animations, **shadows** and much more"

Second item...

"A lot of customization"

**Comment by vaxerski** [comment]
adding shadows to layers is dumb and will bring more issues than it solves:

layers are almost never rectangular, yet their surface has to be (aka, shadow will stick out at the corners

many layers have "segments", again, we will not be able to make a proper shadow

No.

Every damn layer I've seen has options to add a shadow itself. QT, GTK, both are able to do this.

I don't want 20 idiots in my issue tracker every month saying "man my shadow doesnt round with my bar!!!!

The _only_ reason why it works with windows is that almost all windows are rectangular (gtk sometimes aint, so fuck you, gtk)

**Comment by hhhorb** [comment]
> aka, shadow will stick out at the corners

Eww, I hate when I see that with other compositors.

> I don't want 20 idiots in my issue tracker every month saying "man my shadow doesnt round with my bar!!!!

Understandable! thanks for taking the time to respond. :+1:

**Comment by SsubezZ** [comment]
> Every damn layer I've seen has options to add a shadow itself. QT, GTK, both are able to do this.

rofi?

**Comment by markg85** [comment]
Hi!

I think this needs to be reopened and reconsidered.
I've just spend a good part of a day trying to implement shadows in dunst. Along with some AI help i did manage to get there and it looks... fugly as hell:

![Image](https://github.com/user-attachments/assets/e3eb2afc-4c0f-4059-af59-35bfb98f93a3)

Why?
A couple reasons.
1. **Without** compositer blur the shadow looks just fine. But then (semi-)transparent windows are really not usable.
2. Shadow **is** blur, that's how you get shadow.
3. You don't want to do this client side because that breaks app consistency.
4. Also, you don't want to do it client side because the compositer can doe it on the gpu with shaders, that's triky on the cliet side.
5. The client side doesn't know what is behind the app making blur and shadow highly impractible

Now there will be contested opinions here. People favoring one or the other. The literally decades old server side rendering vs client side. Both solutions are a massive pain in the ass.
**Client:** PITA because of the above reasons though you can come up with dozens more.
**Server:** PITA because it too doesn't know where the client wants to have that shadow.

I see a few ways forward here.
1. KDE in the past (or still to this day?) lets the app register a mask to their compositor. It then does everything (blur and shadows).This does mean the app needs a little bit of desktop specific knowledge, not great.
1.1. Yes, this should be a UI toolkit job (aka GTK and Qt). Well, good luck getting them to agree on this.
1.2. It could be a new wayland protocal... And good luck with that.
2. The layer rules in hyprland need to be expanded a little so that i can tell it to blur a rectangle with a given radius and a given offset. So in the case of a notification it would blur the content behind the notification itself, not the shadow. This is probably the easiest but also a very fragile option.
3. I don't know if window properties are a thing in wayland, i guess they are. You can ask a program to add a property "BLURMASK" which would then in a few bytes in the property itself describe the mask. That would make it still completely desktop agnostic for the application. It could be as simple as a [300,200,10] (a 300x200 mask with a radius of 10) which hyprland then would apply to the center whatever layer has this property. So no positional arguments are provided, just a size.


Let me know what you think! Looking forward to getting this somewhere as it really beautifies the desktop and in my opinion totally fits in hyprland!

**Comment by vaxerski** [comment]
the reason it looks ugly is because you used some idiotic ai agent instead of reading the wiki yourself and getting a better solution.

**Comment by markg85** [comment]
> the reason it looks ugly is because you used some idiotic ai agent instead of reading the wiki yourself and getting a better solution.

You really have tone down your condescending arrogant behavior! It's not the first time you answer me in such a blunt way. This definitely happens *a lot* with you.

I've spend close to all day hacking on a project that had no shadow at all. Layers have no shadow (windows do). So, why don't you, instead of gloating, just be helpful. I went over the wiki, no solution there. I went through bug reports (hence responding on this one instead of opening a new one). I'm even trying to come up with ideas and am willing to help! It should be clear that I put in the effort here.

What do I get. Well, you...

For the record with ai. It's not like I'm "vibe coding". I very much use it as a tool where I'd otherwise google and find it either in the docs or stack overflow. I still touch every line of code and more often have to do a lot still to get it working. So do *not* use that as the next excuse to be an asshole.

**Comment by SsubezZ** [comment]
do `layerrule = ignorezero, notifications`
or
`layerrule = ignorealpha <x>, notifications`
x is the alpha you probably set on yo background color of shadows smwhere on dunst config.

**Comment by markg85** [comment]
Little update here.

As Hyprland merged https://wayland.app/protocols/ext-background-effect-v1 having **proper** layer shadows should be possible. Just draw the shadow around the mask that had been set for the blur area.

Ideally that protocol would get some more flags one of which being shadow. Till we get there, if ever, perhaps it's easier to just consider it the mask to draw shadows around if they are enabled. In that same mindset i would also consider enabling/disabling of shadows to be a property that applies equally to windows and layers.
