### ISSUE TITLE
Bad performance unless I use "intel_gpu_frequency -m"

### ISSUE THREAD

**Issue by Cheesemassacre** [hyprwm/Hyprland#5377]
### Hyprland Version

<details> <summary>System/Version info</summary>

Hyprland, built from branch HEAD at commit c5e28ebcfe00a510922779b2c568cfa52a317445  (props: bump ver 0.37.1).
Date: Sat Mar 16 14:51:49 2024
Tag: v0.37.1

flags: (if any)

System Information:
System name: Linux
Node name: archlinux
Release: 6.8.2-zen2-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Thu, 28 Mar 2024 17:06:20 +0000

GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller [8086:0412] (rev 06) (prog-if 00 [VGA controller])

os-release: NAME="Arch Linux"
</details>

### Bug or Regression?

Bug

### Description

If I don't use Intel gpu frequency then performances and animations like switching workspaces, opening and closing windows, moving windows... are very laggy. Scrolling in browsers is laggy too. I have the same problem on a mid 2012 Macbook Air with i3 3317u.

If I use Intel gpu frequency then everything works fine. Intel gpu top is showing similar gpu clocks with and without it. 

PC specs:
i5 4590
HD 4600
8gb ram

### How to reproduce

Use Hyprland on Sandy Bridge or Haswell igpu.

**Comment by vaxerski** [comment]
so what you are saying is "if I make my igpu run on low power, stuff lags."

That's expected...

**Comment by vaxerski** [comment]
it's a problem with how igpus work, and will happen on every wlroots compositor. Major DEs cheat by forcing your clocks up with tricks like triple buffering, which is wasteful.

igpus do not ramp up clocks because hyprland isn't demanding enough, but can't push out more frames when animations happen because they stay at low clocks.

> Things should work normally ootb without using some aditional tools.

in a DE, sure. We aren't one. It's up to you to configure stuff.
