### ISSUE TITLE
[feature request] animations for grid layout

### ISSUE THREAD

**Issue by gmankab** [hyprwm/Hyprland#5491]
### Description

there is a plugin that adds grid layout - https://github.com/thrombe/hyprkool

it says:

> afaik there is no way to control which side the workspaces slide from as a hyprland plugin, so i recommend either turning off animations for workspaces or using animation styles that do not have directionality. (eg fade)

so, can you please let plugins to control animations?

**Comment by vaxerski** [comment]
you can.

hook `CWorkspace::startAnim`

save value of `m_fAlpha.m_pConfig->pValues->internalStyle`

if you want a vertical animation: set style to slidevert
if you want a horizontal animation: set style to slide

call original with `left` set to true for sliding from the left or from the top, false otherwise

restore `m_fAlpha.m_pConfig->pValues->internalStyle`

done

**Comment by gmankab** [comment]
thank you
