### ISSUE TITLE
xkb deadkeys not working despite registering

### ISSUE THREAD

**Issue by Motodavide** [hyprwm/Hyprland#5625]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759  (props: bump version to 0.39.1).
Date: Tue Apr 16 16:01:03 2024
Tag: v0.39.1, commits: 4460

flags: (if any)


System Information:
System name: Linux
Node name: davtoo
Release: 6.6.21-gentoo-dist
Version: #1 SMP PREEMPT_DYNAMIC Wed Mar  6 20:25:11 '00 2024


GPU information:
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD-ATI] Navi 23 [Radeon RX 6650 XT / 6700S / 6800S] [1002:73ef] (rev c1) (prog-if 00 [VGA controller])


os-release: NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"
VERSION_ID="2.14"


plugins:

```

</details>

### Bug or Regression?

Bug

### Description

Despite having set ```xkb_layout=us``` ```xkb_variants=altgr-intl``` with ```xkb_options=compose:menu,lv3:ralt_switch``` dead keys don't work while ```Ralt + ``` _key_ do.

Although ```wev``` registers dead keys correctly, they just don't get typed on any window/program/terminal.

I tried changing settings like ```xkb_options=level3:ralt_switch```, ```xkb_options=<empty>```, even modifying ```/usr/share/X11/xkb/symbols/us``` directly without luck.

### How to reproduce

Set any ```us``` keyboard variant with dead keys

**Comment by ordy** [comment]
Hmm shouldn't it be `kb_layout` and `kb_variant` and not `xkb_layout`? :thinking:

**Comment by Motodavide** [comment]
You're right, I misremembered with all of that troubleshooting. My configs are correct however

**Comment by ordy** [comment]
That's weird, dead keys work for me on default us intl and my own custom layout.

**Comment by vaxerski** [comment]
this is not a hyprland issue, thats handled by xkb

**Comment by ericnantel** [comment]
I am hoping we can reopen this issue as I cannot type most characters with accents using dead keys on Hyprland only. 

I use a French-Canadian keyboard layout:

kb_layout: ca
kb_variant: fr
kb_options: ctrl:nocaps

For reference: [Layout](https://kbdlayout.info/kbdca)

For instance, the expected behaviour when typing ` followed by a should print à 
However only a gets printed.
All deadkeys aren't working.
I tried on all applications I could think of.

Once again, only on Hyprland I am having issues with my keyboard layout. Perhaps it is because on Ubuntu 25.10 it uses an xWayland session, can't say.

Merci.
