### ISSUE TITLE
Gtk-layer-shell window loses (mouse?) focus on workspace change

### ISSUE THREAD

**Issue by xDarksome** [hyprwm/Hyprland#609]
Seems kinda like regression, works fine on 11 days old version.

I have a gtk-layer-shell status bar, unfocusable (keyboard wise). There is a gtk `EventBox` on it, which catches mouse wheel events and switches workspaces.

When I place mouse cursor on the `EventBox` and start scrolling around the current workspace do switch a couple of times and then gets stuck.

Moving cursor a little unstucks the thing until it gets stuck again.
It seems like, despite the fact that the cursor stays rendered on the same spot, its actual position jumps into some oblivion and then restores itself after I do some mouse movement.

I have noticed that previously when I was switching workspaces via my status bar the active window indicator (border) stayed on the previous workspace until I moved the mouse cursor over some window on the current workspace.
Currently, that is not the case and the active window changes immediately after the workspace changes.
May be related.

I will try to identify which commit exactly broke it on the weekends. But maybe you already have some clues.

**Comment by vaxerski** [comment]
> I will try to identify which commit exactly broke it on the weekends. But maybe you already have some clues.

I don't. Please do.

**Comment by ManEnfu** [comment]
Might be related, but is seems that mouse focus on a gtk-layer-shell window gets stuck when the focus switched at the same time it is receiving a mouse event. And the problem has existed for a long while.

In my case, I have an eww status bar with a button that spawns a rofi launcher (or any other window), and other buttons for other purposes. When I click the button, the focus switches to the launcher, but the bar gets stuck and wherever I click on the bar (including other buttons), it activates the last event (which is to spawn the launcher) . I managed to work around this issue by delaying the command call after the button is clicked.

In xDarksome's case, the issue seems to be that the commit https://github.com/hyprwm/Hyprland/commit/dacaf72e02b8d1819135f6aef3911e8211e98630 causes focus to switch in the event of workspace change no matter what. So the mouse wheel event on the bar causes focus to switch, while the bar is still receiving the event.

**Comment by xDarksome** [comment]
@ManEnfu 

> In my case, I have an eww status bar with a button that spawns a rofi launcher (or any other window), and other buttons for other purposes. When I click the button, the focus switches to the launcher, but the bar gets stuck and wherever I click on the bar (including other buttons), it activates the last event (which is to spawn the launcher)

Can confirm, encountered the same behavior, but it didn't bother me as much as the workspace switching issue.

> I managed to work around this issue by delaying the command call after the button is clicked.

How much of a delay are we talking?

> In xDarksome's case, the issue seems to be that the commit https://github.com/hyprwm/Hyprland/commit/dacaf72e02b8d1819135f6aef3911e8211e98630 causes focus to switch in the event of workspace change no matter what. So the mouse wheel event on the bar causes focus to switch, while the bar is still receiving the event.

I will check whether this is the commit that broke it. Thanks for the head start!

**Comment by xDarksome** [comment]
Well, this is definitely it. 
Moreover, https://github.com/hyprwm/Hyprland/commit/dacaf72e02b8d1819135f6aef3911e8211e98630 places the mouse cursor in the center of an active window after workspace switch.

**Comment by vaxerski** [comment]
`general:no_cursor_warps` ?

**Comment by xDarksome** [comment]
Oh, that's a feature, I see.

Yea, that disables the mouse centering, but workspace scrolling issue persists.

**Comment by xDarksome** [comment]
I don't think this particular commit is the problem. It just made the problem more obvious.
Seems like @ManEnfu is really into something with window focusing.

I couldn't reproduce this in sway btw
> In my case, I have an eww status bar with a button that spawns a rofi launcher (or any other window), and other buttons for other purposes. When I click the button, the focus switches to the launcher, but the bar gets stuck and wherever I click on the bar (including other buttons), it activates the last event (which is to spawn the launcher)

**Comment by vaxerski** [comment]
check with f4add0ac6d633379ade7470a5e6b4afd45f4a073

**Comment by xDarksome** [comment]
Works like a charm, thanks!

The issue originally mentioned by @ManEnfu is fixed as well.
