### ISSUE TITLE
screen rotate and keyboard not working in tablet mode and fingerprint not working in convertible laptops (HP X360 1030 G2)

### ISSUE THREAD

**Issue by Iamloumie** [hyprwm/Hyprland#6191]
i use an HP X360 1030 G2, but when i rotate my screen in tablet mode, the screen doesn't rotate, if i try to type as well, the virtual keyboard does not automatically pop up, i have installed onboard and other virtual keyboards, i've used hyprland wiki to try and get a solution but the story is still the same.... PLEASE, assist with a config script/file that senses when the screen is in tablet mode and can rotate automatically, plus the keyboard should also autostart in the tablet mode as well.. and finally, the fingerprint config file/script, so that there can be option of password/fingerprint in the login...... thank you so much for your time, i hope i get a reply soon

**Comment by vaxerski** [comment]
hyprland is very much a DIY experience - and stuff for everything you ask for is likely doable with scripts or external tools (e.g. https://github.com/JeanSchoeller/iio-hyprland/ )

OSK are external clients and hyprland does not provide one

**Comment by jacekpoz** [comment]
not sure if this is my skill issue or if your tablet protocol rewrite broke it but before it setting
```
input {
  touchdevice {
    output=eDP-1
  }
  tablet {
    output=eDP-1
  }
```
in the config and using [rot8](https://github.com/efernau/rot8) made it all work

right now I switched to iio-hyprland and still needed to apply [this patch](https://github.com/JeanSchoeller/iio-hyprland/pull/14) on top of it and that config to make it work

aside from that using a stylus on my laptop has been terrible since that got merged, I'll record some videos and make an issue soon (if there isn't one already)
