### ISSUE TITLE
Some window started opening with expand animation

### ISSUE THREAD

**Issue by ArttX** [hyprwm/Hyprland#6494]
### Bug or Regression?

Bug

### System Info and Version

Worked normal with same config.

### Description

When opening rofi window in 0.40.x versions, some window started to open with expand animation.
Using same rofi for each windows, but some opening with expand animation. 

### How to reproduce

1. Open rofi dmenu.
2. Open different type rofi applet.
3. Difference in animation

### Crash reports, logs, images, videos

Hyprland, built from branch main at commit 8055b1c00a102f5419e40f5eddfb6ee8be693f33  (misc: Fix build warnings (6486)).
Date: Fri Jun 14 00:23:23 2024
Tag: v0.41.1-4-g8055b1c0, commits: 4822

**Comment by vaxerski** [comment]
what do you mean expand? Can you record the problem?

**Comment by ArttX** [comment]
Sorry. Took video, but forgot to add it.

[Kooha-2024-06-14-11-39-36.webm](https://github.com/hyprwm/Hyprland/assets/63876301/7c512124-e299-46ad-b94e-3ec3be0ef198)
Notes applet is doing slow expand animation and notes applet do not (appears immediately).

**Comment by vaxerski** [comment]
is it perhaps that you have animations enabled for the layer and the layer resizes after creation?

**Comment by vaxerski** [comment]
try setting animation leaf `layers` to disabled

**Comment by ArttX** [comment]
> try setting animation leaf `layers` to disabled

What it means? Using Linux for 2 months only.

**Comment by tchofy** [comment]
Just add `layerrule=noanim,rofi` to your config file and it should disable animations specifically for rofi. If you want to keep the animations but customize them to be different/faster, you can check the [Animations section in the wiki](https://wiki.hyprland.org/Configuring/Animations/) for more info.

If you want to disable animations for any other specific layersurface, replace `rofi`  with the layer's namespace, you can find it with the command `hyprctl layers` while the layersurface is on screen. If you can't use a terminal and a layer at the same time because they grab input focus (like with rofi), you can just do `sleep 2 && hyprctl layers` then use the keybind to make the layer show up within this 2 second period.

**Comment by ArttX** [comment]
@tchofy Thanks! It works and removed animation.
But there is still visual difference when opening rofi windows. Example, now some rofi windows open in 2 frames, where one frame is shrinken window and other is expanded. Other windows appear in one frame.
I looked deepier in my used applets and see, that this is happening for dynamic list applets - that is, applets that executes command to get list of items, opens rofi window and then renders list, so that's why there is 2 frames.
It is strange question, but do it is possible to make rofi display window, when list is created?

**Comment by vaxerski** [comment]
> But there is still visual difference when opening rofi windows. Example, now some rofi windows open in 2 frames, where one frame is shrinken window and other is expanded. Other windows appear in one frame.

That's a rofi thing, go complain to the devs there.

Anyways, solved
