### ISSUE TITLE
Add the ability to view multiple workspaces at the same time

### ISSUE THREAD

**Issue by amarakon** [hyprwm/Hyprland#6882]
### Description

DWL and River only have nine workspaces, but if you press mainMod + 0, all the workspaces are visible at the same time. Also, if you press mainMod + Control + *number*, that toggles that workspace. It would be cool if something similar existed in Hyprland.

**Comment by fufexan** [comment]
I believe you're looking for something akin to [hyprexpo](https://github.com/hyprwm/hyprland-plugins/tree/main/hyprexpo).

**Comment by zakk4223** [comment]
I don't think they want an overview, they want workspaces to work differently. 

I think with a combination of window tagging and maybe a small plugin you could do it.  Might even be able to do it with an external script. Either way it would be a bit of a hack because you'd either have to hide/unhide windows or move them to a 'hidden' workspace and back.

**Comment by donovanglover** [comment]
Have you tried [hyprtags](https://github.com/JoaoCostaIFG/hyprtags)?

**Comment by amarakon** [comment]
> Have you tried [hyprtags](https://github.com/JoaoCostaIFG/hyprtags)?

Thanks, I didn't know about hyprtags. I tried it and it's basically what I want. However, it's kind of buggy. I think It should be built in to Hyprland.

**Comment by zakk4223** [comment]
If it is buggy then file github issues and maybe the developer will fix them. My suspicion is the workspace model of Hyprland is unlikely to change, and the response will be 'use a plugin'

**Comment by vaxerski** [comment]
@zakk4223 is right.
