### ISSUE TITLE
Cursor scaling issues after aquamarine

### ISSUE THREAD

**Issue by leiserfg** [hyprwm/Hyprland#7162]
### Regression?

Yes

### System Info and Version

Hyprland in [master](https://github.com/hyprwm/Hyprland/commit/4141e6755022edc19cd37cd7ad077a93b3bae5bd)

### Description

After aquamarine cursors rendered by hyprland don't scale with the monitor.

### How to reproduce

If you have both `HYPRCURSOR_SIZE` and `XCURSOR_SIZE` set to 16 and you scale the monitor to 2  the XCursors looks fine but the hyprcursors looks tiny. 
One can workaround it by setting HYPRCURSOR_SIZE to `2 *  XCURSOR_SIZE` but that will break in other monitors.

**Comment by vaxerski** [comment]
bisect please

**Comment by vaxerski** [comment]
odd because on my laptop all is good and I use 1.5

**Comment by leiserfg** [comment]
I tried with a commit in the middle of the aquamarine pr and got the same, now I'm far from the laptop and partially drunk so I'll keep binary searching when I go back home.

**Comment by leiserfg** [comment]
I was trying to bisect but given that during aquamarine development, you were updating all the components in parallel it's very hard to know when the error happened for the first time (as I can't compile some commits cause nix was broken at that point). For what I managed to test:
29598f2c503f24177878202d67db8657da36ea5e seemed to still be fine, but 648b7b3b6d58caa472c76d3f7e99d332b92df0eb was already broken. If you have any clue and you wold like to test another of the hundreds of commits let me know 😄

**Comment by MahouShoujoMivutilde** [comment]
I've found it, 1d4e5187 is the first bad commit.

Building 5dd2c27b631f16e49a2c6e6cbbefba9fa50bf543 + aquamarine a70fc6a (latest atm) with

```
git revert -n 1d4e5187
```

Completely fixes the scaling problem for me, regardless of values of `cursor:enable_hyprcursor`, `cursor:allow_dumb_copy` and `cursor:no_hardware_cursors`.

Not sure if it's a proper fix though.

---

All the bisecting is on aquamarine 0ab8ffa, a bit outdated, because I initially misremembered that the cursor was fine until recently, and tried to see if it was aquamarine that broke it.

It wasn't fine. It's just that the issue only manifests for me when hovering over swaybg.

<details><summary>Details</summary>
<p>
Cursor:

BAD 8a5f9bbb keybinds: handle null monitor in pinActive (7122)

BAD r5027.cc7c117f-1 - pre-locks pr?

Further:

BAD 8a5f9bbb keybinds: handle null monitor in pinActive (7122)
....
BAD 5979ceb5 surface: fixup logical damage size calculations

Further:

BAD 016da234 move to aquamarine

Bisecting the aquamarine MR:

BAD 4b840296 rerun pipeline
cedac20c flake: update aquamarine
aa1ebc51 fix possible crash 3
78d11c45 fix possible crash 2
1c5c905c fix crash
8dbaef29 flake: update aquamarine
1d933293 fix
8aff9713 fix crashas
70e46701 oopsie daisy
85cf0972 flake.lock: update aq
1f844610 [aquamarine] try to fix direct scanout (6875)
0de9568d eee
a3770ab8 use output state format
a0ec9261 logs
ed8b4b73 shm drm woo
557d2ab3 ci: add aq
f059851c flake.lock: update
65b041dd format
c4913662 Aquamarine headers for no pch build and a heap use after free (6892)
supposedly BAD 648b7b3b CI/Arch: add libxcursor
b8192420 flake.lock: update
b59c159d thanks virt
e444d2a1 Hw cursors fix for nvidia (6847)
af4a1345 thanks ikalco
955ee5f1 thanks ikalco
BAD fe2fe1f3 viewporter stuff
8ea06338 add scheduleFrame reasons (6799)
BAD aa6ae138 make explicit sync setting actually disable it
BAD d786094f stuff
CRASH 62896129 reset explicit fences before commit (6841)
0f09940c fix xwayland crash
38867021 better
1fcb8cc1 swapchain test stuff
CRASH 805a0543 Explicit sync fixes (6829)
CRASH 4c905b1a ok gulafaran
cdd037ec initialize arrays
8ae38c1e stuff
13af7fb2 explicit sync stuff
37a96c61 [gha] Nix: update inputs
95ddf9e7 stuff for aq alloc split
959e83fd stuf
FAIL d13189d8 no leakeroni
1d4e5187 e
45f726c6 dmabufff
be4051e9 send flag on main tranche
f472dcd6 ds fixes
76b8be23 some fixes to dmabuf
FAIL 4aa77b26 fixeroni crasheroni
FAIL (supposedly GOOD) 29598f2c flake.lock: update
bd25149d Nix: add xcursor dep
05f7a239 nix: drop unused script after 589f758d947c
d7aded85 cmake: drop unused include after 758c0b325333
8cf770b7 meson: unbreak build with aquamarine
1a1cc59c flake.lock: update aquamarine
ab428222 fix crasheroni
c9fdf622 fixes
e36c1e9b log mismatched fds
1b4a5fc4 stuf
2fd90132 dont crash on multigpu lol
e09e76aa avoid spam
09af47a4 cursorsss
f4c8789a explicit sync
82e27597 xcursors mmm
c6b9b292 fix mirrors, thanks virtcode
74971816 fix
cff9b4fd missed a file
03eb7e37 xcursor stuff
FAIL 590e706c damage oops
92357281 fix nvidia crasherino lmao
360673ed fix small ub in keyboard
c03f25e6 rid of wlr more
...

FAIL means
```
    [128/248] Building CXX object CMakeFiles/Hyprland.dir/src/managers/KeybindManager.cpp.o
    /build/hyprland-my-aquamarine-git/src/hyprland/src/managers/KeybindManager.cpp: In static member function ‘static uint64_t CKeybindManager::spawnRaw(std::string)’:
    /build/hyprland-my-aquamarine-git/src/hyprland/src/managers/KeybindManager.cpp:905:14: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
    905 |         write(socket[1], &grandchild, sizeof(grandchild));
    |         ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /build/hyprland-my-aquamarine-git/src/hyprland/src/managers/KeybindManager.cpp:912:9: warning: ignoring return value of ‘ssize_t read(int, void*, size_t)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
    912 |     read(socket[0], &grandchild, sizeof(grandchild));
    |     ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ninja: build stopped: subcommand failed.
    make: *** [Makefile:15: release] Error 1
    ==> ERROR: A failure occurred in build().
    Aborting...
    ==> ERROR: Build failed, check /var/lib/aurbuild/x86_64/witch/build

```

Attempting to `git cherry-pick -n d786094f` on crashes:

BAD d786094f stuff
OLD CRASH 62896129 reset explicit fences before commit (6841)
0f09940c fix xwayland crash
38867021 better
1fcb8cc1 swapchain test stuff
OLD CRASH 805a0543 Explicit sync fixes (6829)
BAD 4c905b1a ok gulafaran
cdd037ec initialize arrays
8ae38c1e stuff
BAD 13af7fb2 explicit sync stuff
37a96c61 [gha] Nix: update inputs
BAD 95ddf9e7 stuff for aq alloc split
FAIL 959e83fd stuf
FAIL d13189d8 no leakeroni
1d4e5187 e
45f726c6 dmabufff
be4051e9 send flag on main tranche
f472dcd6 ds fixes
76b8be23 some fixes to dmabuf
FAIL 4aa77b26 fixeroni crasheroni
FAIL (supposedly GOOD) 29598f2c flake.lock: update
bd25149d Nix: add xcursor dep
05f7a239 nix: drop unused script after 589f758d947c
d7aded85 cmake: drop unused include after 758c0b325333
8cf770b7 meson: unbreak build with aquamarine
1a1cc59c flake.lock: update aquamarine
ab428222 fix crasheroni
c9fdf622 fixes
e36c1e9b log mismatched fds
1b4a5fc4 stuf
2fd90132 dont crash on multigpu lol
e09e76aa avoid spam
09af47a4 cursorsss
f4c8789a explicit sync
82e27597 xcursors mmm
c6b9b292 fix mirrors, thanks virtcode
74971816 fix
cff9b4fd missed a file
03eb7e37 xcursor stuff
FAIL 590e706c damage oops
92357281 fix nvidia crasherino lmao
...

Attempting to `git cherry-pick -n 95ddf9e7 d786094f` to fix build failing and crashes (probably because of newer aquamarine than it was written for)

BAD 95ddf9e7 stuff for aq alloc split
OLD FAIL 959e83fd stuf
OLD FAIL d13189d8 no leakeroni
BAD 1d4e5187 e
GOOD 45f726c6 dmabufff
GOOD! but can't click on some buttons be4051e9 send flag on main tranche
f472dcd6 ds fixes
76b8be23 some fixes to dmabuf
OLD FAIL 4aa77b26 fixeroni crasheroni
OLD FAIL (supposedly GOOD) 29598f2c flake.lock: update

Result:

1d4e5187 is first bad commit.

</p>
</details>

**Comment by vaxerski** [comment]
does #7178 fix this>

**Comment by leiserfg** [comment]
#7178 does not fix it, but reverting 1d4e5187 from master does it.

**Comment by vaxerski** [comment]
@gulafaran can you integrate this to #7178? seems to make sense

**Comment by gulafaran** [comment]
> @gulafaran can you integrate this to #7178? seems to make sense

will do

**Comment by gulafaran** [comment]
pushed to #7178 , added a size check inside getShape and reload theme incase scale changed. should get the previous behaviour back.

**Comment by MahouShoujoMivutilde** [comment]
With default `cursor:...` it works and the issue with scale is indeed fixed.

However, when `no_hardware_cursors = yes` there is some seemengly damage problems that even `damage_tracking = 0` doesn't fix.

![05-08-2024-00_29_14-cropped](https://github.com/user-attachments/assets/1198409d-d1cd-4152-87b9-3df329e7b3ea)

`allow_dumb_copy = yes` also makes the cursor approximately 2 times bigger. But only `no_hardware_cursors = yes` causes artifacts on cursor.

**Comment by gulafaran** [comment]
il see if i can reproduce tomorrow its getting late heh

> With default `cursor:...` it works and the issue with scale is indeed fixed.
> 
> However, when `no_hardware_cursors = yes` there is some seemengly damage problems that even `damage_tracking = 0` doesn't fix.
> 
> ![05-08-2024-00_29_14-cropped](https://private-user-images.githubusercontent.com/14999778/354930384-1198409d-d1cd-4152-87b9-3df329e7b3ea.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4MDgwOTksIm5iZiI6MTcyMjgwNzc5OSwicGF0aCI6Ii8xNDk5OTc3OC8zNTQ5MzAzODQtMTE5ODQwOWQtZDFjZC00MTUyLTg3YjktM2RmMzI5ZTdiM2VhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA0VDIxNDMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3MTg1MTEzZTJmZjI3NzU5NjQ0ZTJkMmYxMjg1Y2I1OGFjYjM5ZjI1ZTI3M2RjNDBkZGNlNDVhNGJkNmQyNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ee_IRcLrKflqqErE1bksnXmpDiI7Nmr04i1SpXIFR6w)
> 
> `allow_dumb_copy = yes` also makes the cursor approximately 2 times bigger. But only `no_hardware_cursors = yes` causes artifacts on cursor.

artifacts at all times, and 2 times bigger at all times or do i need two monitors with different scaling to reproduce? thought id ask and il see if i can reproduce it

**Comment by MahouShoujoMivutilde** [comment]
Artifacts as soon as I set `cursor:no_hardware_cursors = yes` and reload config, maybe move mouse a bit, scale set 1.25, single monitor, on nvidia. No artifacts with hardware cursors enabled.

Two times bigger immediately after setting `allow_dumb_copy = yes` and reloading config, no other actions.

Those are two separate effects that can be combined when the said options are both `yes`.

**Comment by gulafaran** [comment]
> Artifacts as soon as I set `cursor:no_hardware_cursors = yes` and reload config, maybe move mouse a bit, scale set 1.25, single monitor, on nvidia. No artifacts with hardware cursors enabled.
> 
> Two times bigger immediately after setting `allow_dumb_copy = yes` and reloading config, no other actions.
> 
> Those are two separate effects that can be combined when the said options are both `yes`.

thanks il see what i can find <3

**Comment by gulafaran** [comment]
> Artifacts as soon as I set `cursor:no_hardware_cursors = yes` and reload config, maybe move mouse a bit, scale set 1.25, single monitor, on nvidia. No artifacts with hardware cursors enabled.
> 
> Two times bigger immediately after setting `allow_dumb_copy = yes` and reloading config, no other actions.
> 
> Those are two separate effects that can be combined when the said options are both `yes`.
> 
> So yes, at all times as soon as options are set.

does it occur on #7178 now? there was a heap use after free going on

**Comment by MahouShoujoMivutilde** [comment]
No, it's fixed completely in both cases.

https://github.com/user-attachments/assets/e8a27fea-d31d-45ce-b5d2-b8c5ca16a48a

**Comment by gulafaran** [comment]
nice :)
