### ISSUE TITLE
Backlit of my custom keyboard is not working even after the command

### ISSUE THREAD

**Issue by piyushyadav0191** [hyprwm/Hyprland#7344]
### Regression?

Yes

### System Info and Version

https://justpaste.it/fh1qf

### Description

My backlit used to work when I uninstalled hyprland months ago. Today, i installed hyprland and everything works fine but backlit is not wokring. 
My backlit blinks for a second if i write this command but it only blinks `sudo sh -c 'echo 1 > /sys/class/leds/input24::scrolllock/brightness'`

### How to reproduce

1. Opens terminal and write both command - xset led on && sudo sh -c 'echo 1 > /sys/class/leds/input24::scrolllock/brightness'
2. backlit blinks for a second and stops
3. again type command then it blinks and stops

**Comment by vaxerski** [comment]
excuse me but why is your keyboard's backlight the scroll lock LED?

**Comment by piyushyadav0191** [comment]
@vaxerski It's a custom embed setting from the keyboard. In Windows, it starts with the Fn key + Scroll Lock. Even on Arch Linux, I can enable it through `xset led on`, but on Hyprland, I cannot enable it using `xset led on` or by running `sudo sh -c 'echo 1 > /sys/class/leds/input24::scrolllock/brightness'`.

**Comment by vaxerski** [comment]
xset is for X. It won't work on wayland.

ATM, there is no mechanism to forcefully lock LED states in hyprland. You could patch hyprland yourself for that though

**Comment by piyushyadav0191** [comment]
@vaxerski okay but can you tell me why `sudo sh -c 'echo 1 > /sys/class/leds/input24::scrolllock/brightness' ` not working because I used this command couple month ago in my previous hyprland setup and it was turning my LED on but now its not, why?

**Comment by vaxerski** [comment]
hyprland takes full control of your LEDs, if scroll lock is not enabled in hyprland, the LED will be disabled next time hyprland updates the LED states.

**Comment by piyushyadav0191** [comment]
@vaxerski So there is no way to get LED enabled ? What do i have to do to patch my hyprland for my LED problem

**Comment by vaxerski** [comment]
IKeyboard.cpp@290

you need to find your numlock LED index and make the value `val | (1 << idx)`

```cpp
updateLEDs(leds.value() | (1 << numlockLedIndex));
```

**Comment by piyushyadav0191** [comment]
Okay, Thanks

**Comment by vaxerski** [comment]
because hyprland controls your leds

**Comment by camballe** [comment]
After extensive troubleshooting, I found a working solution by modifying Hyprland's source code to force persistent control of the Scroll Lock LED. For anyone experiencing similar issues with keyboard backlights not persisting, here's the fix:

```cpp
// In src/devices/IKeyboard.cpp
void IKeyboard::updateLEDs(uint32_t leds) {
    if (!xkbState || !aq())
        return;

    // Force Scroll Lock LED to stay on (bit 2 corresponds to Scroll Lock)
    const uint32_t FORCED_LEDS = leds | (1 << 2); 
    
    aq()->updateLEDs(FORCED_LEDS);
}
```

**Steps:**  
1. Locate the `updateLEDs` function in `IKeyboard.cpp`  
2. Add the forced LED bitmask as shown above  
3. Rebuild Hyprland:  
```bash
meson build && ninja -C build && sudo ninja -C build install
```

**Key Details:**  
- Forces Scroll Lock LED persistence via bitmask modification  
- LED index `2` works for Scroll Lock in most configurations  
- Survives replugs/restarts  
- Toggle functionality sacrificed for persistence  

**Verification:**  
```bash
echo 1 | sudo tee /sys/class/leds/inputX::scrolllock/brightness
```

Would the Hyprland team consider making this configurable? Happy to help implement a toggleable version via PR if interested.

---

Replace `inputX` with your device number (e.g., input4).  
This worked for my LimeLide keyboard where Hyprland's LED control was too aggressive.

**Comment by EmpireOperating** [comment]
A configuration-only workaround avoids the source patch and preserves normal toggling for keyboards whose backlight is wired to the Scroll Lock LED.

On Hyprland 0.56.2, direct writes to `/sys/class/leds/inputX::scrolllock/brightness` produced only a brief flash because Hyprland subsequently synchronized the LED back to its XKB state. Adding the standard XKB option below makes Scroll Lock a managed Mod3 state, so Hyprland retains the LED state instead of immediately clearing it:

```
input {
    kb_options = scrolllock:mod3
}
```

If `kb_options` is already set, append the option rather than replacing the existing values. For example:

```
kb_options = compose:caps,shift:both_capslock_cancel,scrolllock:mod3
```

Tested with a SINO WEALTH USB keyboard (`258a:0001`) whose backlight follows the Scroll Lock LED. After reloading Hyprland, the keyboard backlight remained enabled and the physical Scroll Lock key toggled it normally.

This may be useful as a documentation note or troubleshooting recommendation for this class of keyboards; it requires no kernel change, polling service, or locally patched Hyprland binary.
