### ISSUE TITLE
Invisible cursor

### ISSUE THREAD

**Issue by rik-x290** [hyprwm/Hyprland#7577]
### Regression?

Yes, No

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```

</details>

### Description

Cursor is not rendering. I am on amd with open source drivers. Tried Wlr Jo hardware cursors=1 as well. Still no change. I am on arch with latest hyprland version. Tried the git version as well. Nothing changed.

### How to reproduce

Don't know

**Comment by coltwillcox** [comment]
+1

**Comment by coltwillcox** [comment]
My temp fix was to downgrade those packages from last night update (to the left side version, with downgrade tool):
* mesa (1:24.1.6-1 -> 1:24.2.1-1)
* lib32-mesa (1:24.1.6-1 -> 1:24.2.1-1)
* libva-mesa-driver (1:24.1.6-1 -> 1:24.2.1-1)

So, I guess this maybe is not related to hyprland.

**Comment by neon-JS** [comment]
+1

**Comment by moetayuko** [comment]
A temp workaround is to disable hw cursor
```
cursor {
    no_hardware_cursors = true
}
```

**Comment by vaxerski** [comment]
maybe worth opening an issue over at mesa then?

**Comment by Frestein** [comment]
> maybe worth opening an issue over at mesa then? I obviously can't for known reasons
> 
> edit: fwiw, rx 6700 xt, updated mesa and I still have a cursor

RX 580, updated mesa and now I have an invisible cursor.

I am using Arch Linux, the problem is reproducible on hyprland and hyprland-git.

**Comment by vaxerski** [comment]
can you post a trace log? https://wiki.hyprland.org/Crashes-and-Bugs/#obtaining-a-trace-log

**Comment by nadomodan** [comment]
everyone reporting this issue seems to be using a Polaris GPU https://gitlab.freedesktop.org/mesa/mesa/-/issues/11817

**Comment by vaxerski** [comment]
could be an issue in mesa but I am interested in a trace log so that I can also see whats up if its not my issue

**Comment by nadomodan** [comment]
[hyprland.log](https://github.com/user-attachments/files/16826118/hyprland.log)

**Comment by vaxerski** [comment]
ok nothing looks amiss

**Comment by moetayuko** [comment]
@vaxerski The cause is similar to the one I fixed when initially moving to aquamarine. Here are the cursor BO allocation steps: https://github.com/hyprwm/aquamarine/blob/16bbbcba65c4700b286f9c45d91bb49f2dd3e67c/src/allocator/GBM.cpp#L158-L177

mesa 24.1 behavior on Polaris (good):
```
gbm_bo_create_with_modifiers2 -> nullptr
↓
gbm_bo_create_with_modifiers -> nullptr
↓
gbm_bo_create -> valid ptr
```

mesa 24.2 behavior on Polaris (bad):
```
gbm_bo_create_with_modifiers2 -> valid ptr
```
trace logs:
```
[TRACE] [AQ] GBM: Using modifier-based allocation, modifiers: 1
[TRACE] [AQ] GBM: | mod 0x0
[LOG] [AQ] GBM: Allocated a new buffer with size [Vector2D: x: 128, y: 128] and format AR24 with modifier 72057594037927935 aka INVALID
```

Now that `gbm_bo_create_with_modifiers2` returns a valid ptr but is not usable, the nullptr check is no longer sufficient. HW cursor starts working if I directly use `gbm_bo_create` in aquamarine.

I'm unsure if this is a bug or expected behavior in mesa 24.2.

**Comment by moetayuko** [comment]
> @vaxerski The cause is similar to the one I fixed when initially moving to aquamarine. Here are the cursor BO allocation steps: https://github.com/hyprwm/aquamarine/blob/16bbbcba65c4700b286f9c45d91bb49f2dd3e67c/src/allocator/GBM.cpp#L158-L177
> 
> mesa 24.1 behavior on Polaris (good):
> 
> ```
> gbm_bo_create_with_modifiers2 -> nullptr
> ↓
> gbm_bo_create_with_modifiers -> nullptr
> ↓
> gbm_bo_create -> valid ptr
> ```
> 
> mesa 24.2 behavior on Polaris (bad):
> 
> ```
> gbm_bo_create_with_modifiers2 -> valid ptr
> ```
> 
> trace logs:
> 
> ```
> [TRACE] [AQ] GBM: Using modifier-based allocation, modifiers: 1
> [TRACE] [AQ] GBM: | mod 0x0
> [LOG] [AQ] GBM: Allocated a new buffer with size [Vector2D: x: 128, y: 128] and format AR24 with modifier 72057594037927935 aka INVALID
> ```
> 
> Now that `gbm_bo_create_with_modifiers2` returns a valid ptr but is not usable, the nullptr check is no longer sufficient. HW cursor starts working if I directly use `gbm_bo_create` in aquamarine.
> 
> I'm unsure if this is a bug or expected behavior in mesa 24.2.

It turns out that the bo allocated by `gbm_bo_create_with_modifiers2` can be used. We just need to set its modifier type to `DRM_FORMAT_MOD_LINEAR` (`gbm_bo_get_modifier` returns `DRM_FORMAT_MOD_INVALID`)

PR opened https://github.com/hyprwm/aquamarine/pull/71

**Comment by dougvk** [comment]
Adding a newer datapoint here because the symptom matches, but the stack/signature look a bit different from the old Polaris/Mesa 24.2 reports.

Environment:
- Arch Linux / Omarchy
- Hyprland 0.54.3-2
- hypridle 0.1.7-8
- hyprlock 0.9.3-2
- mesa 26.0.3-1
- linux 6.19.10-arch1-1
- AMD Barcelo / Renoir iGPU (PCI ID 1002:15e7)
- Single 4K external monitor over HDMI

What happened:
- screen flashed
- cursor disappeared
- mouse itself did not actually disconnect
- the machine later hard-froze once in a similar state

Useful signals from the live investigation:
- the mouse was still present in `/proc/bus/input/devices` and still listed in `hyprctl devices`
- `hyprctl monitors` showed only one active monitor, but `hyprctl cursorpos` ended up outside the visible desktop bounds
- Hyprland log contained:
  - `*** BUG *** In pixman_region32_init_rect: Invalid rectangle passed`
- session log also showed repeated output reset/remodeset activity around the failure:
  - `drm: Disabling output HDMI-A-2`
  - `drm: Modesetting HDMI-A-2 with 3840x2160@60.00Hz`

What recovered it:
- setting `cursor { no_hardware_cursors = true }`
- then `hyprctl reload`

After reload, the cursor coordinates snapped back inside the visible monitor area and the pointer became visible again immediately.

So at least on this machine, the problem does not look like a Bluetooth/input disconnect. It looks more like a compositor/output/cursor-geometry failure, with the pixman invalid-rectangle message being the clearest clue.

If this looks unrelated to the older Polaris/Mesa path, I can open a fresh discussion with a sanitized trace/log excerpt.
