### ISSUE TITLE
groups (tabs) in master stack layout

### ISSUE THREAD

**Issue by primalmotion** [hyprwm/Hyprland#770]
Any chance to have the groups (tabs) implemented in master stack layout?

**Comment by vaxerski** [comment]
it's complicated.

the groups currently existing in dwindle are made using method A.

I've had plans to detach method A and instead do it more globally, so that groups would work regardless of the layout.

Like one or two people disliked method A, and created PR #593 which would use method B.

method B *cannot* work as a global method.

So, now I am in a bit of a deadlock - I can't make method A global because it'd upset people from the PR above (unless they give up) and I don't want to implement method A separately to master - duplicating code, thats one, but bugs thats two. I also cannot adapt method B, because no way in hell it would work cross-layouts.

**Comment by primalmotion** [comment]
I see. thanks for the explanation. I've seen this PR already. If method A allows generic tabs, I'm also in support of it too :)
