### ISSUE TITLE
No support for xembed tray icons.

### ISSUE THREAD

**Issue by sblantipodi** [hyprwm/Hyprland#8389]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Info and Version

Arch linux: 2024.11.01
Included Kernel: 6.11.5

### Description

hi there...
I am writing a Java app with JavaFX...
I would like to create a tray icon in Hyprland but it seems that there is now way to make it work with it.
Java uses xmebed legacy method... is it possible to add the support for legacy tray icons in Hyprland?

### How to reproduce

simply test the tray icon support with 
`SystemTray.isSupported()`

**Comment by fufexan** [comment]
Hyprland does not handle trays. No modern bar supports the legacy xembed method, instead using the more modern [StatusNotifierItem](https://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/).

If this is just for testing purposes, you could try using stalonetray or some other X trays, though they will act in unexpected ways due to being run on Wayland.
