### ISSUE TITLE
seatd not launching

### ISSUE THREAD

**Issue by werdahias** [hyprwm/Hyprland#956]
Apologies beforehand if this isn't the right place to file this bugreport. I built Hyprland manually on Debian testing. When I try to launch it, libseat/seatd fails to start (from what I can tell). I should mention I'm running OpenRC. I take it this is the reason it's not working. Any ideas to point me in the right direction?
![error_log](https://user-images.githubusercontent.com/23419969/200110959-2d140b04-efa9-43d4-94bf-c2e0b3d96428.jpeg)

**Comment by vaxerski** [comment]
a lot of permission errors. My best bet is that you have completely broken permissions in your system.

Besides, isn't debian testing too slow with dependencies?

Anyways, that's not a hyprland issue, but a "you can't use linux" issue. Most likely can be fixed by using a distro that has configured stuff properly for you.
